/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SKFCHINA_COMMON_COMMON_PB_H_INCLUDED
#define PB_SKFCHINA_COMMON_COMMON_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Type of measurement */
typedef enum _SKFChina_Common_MeasurementType {
    /* 0 - 63 used */
    SKFChina_Common_MeasurementType_UNKNOWN_MEASUREMENT_TYPE = 0,
    /* Vibration */
    SKFChina_Common_MeasurementType_VIBRATION_ACC_WAVE = 1,
    SKFChina_Common_MeasurementType_VIBRATION_ENV2_WAVE = 2,
    SKFChina_Common_MeasurementType_VIBRATION_ENV3_WAVE = 3,
    SKFChina_Common_MeasurementType_VIBRATION_VELOCITY_WAVE = 4,
    SKFChina_Common_MeasurementType_VIBRATION_ACC_STATUS_WAVE = 63,
    SKFChina_Common_MeasurementType_VIBRATION_ACC_P2P = 5,
    SKFChina_Common_MeasurementType_VIBRATION_ACC_RMS = 6,
    SKFChina_Common_MeasurementType_VIBRATION_ENV2_P2P = 7,
    SKFChina_Common_MeasurementType_VIBRATION_ENV2_RMS = 8,
    SKFChina_Common_MeasurementType_VIBRATION_ENV3_P2P = 9,
    SKFChina_Common_MeasurementType_VIBRATION_ENV3_RMS = 10,
    SKFChina_Common_MeasurementType_VIBRATION_VELOCITY_P2P = 11,
    SKFChina_Common_MeasurementType_VIBRATION_VELOCITY_RMS = 12,
    /* Rotation speed */
    SKFChina_Common_MeasurementType_ROTATION_SPEED = 31,
    /* Enviromental temperature */
    SKFChina_Common_MeasurementType_ENVIROMENTAL_TEMPERATURE_CURRENT = 13,
    SKFChina_Common_MeasurementType_ENVIROMENTAL_TEMPERATURE_MAX = 14,
    SKFChina_Common_MeasurementType_ENVIROMENTAL_TEMPERATURE_MIN = 15,
    SKFChina_Common_MeasurementType_ENVIROMENTAL_TEMPERATURE_HISTORY = 16,
    /* Enviromental humidity */
    SKFChina_Common_MeasurementType_ENVIROMENTAL_HUMIDITY_CURRENT = 17,
    SKFChina_Common_MeasurementType_ENVIROMENTAL_HUMIDITY_MAX = 18,
    SKFChina_Common_MeasurementType_ENVIROMENTAL_HUMIDITY_MIN = 19,
    SKFChina_Common_MeasurementType_ENVIROMENTAL_HUMIDITY_HISTORY = 20,
    /* Board temperature */
    SKFChina_Common_MeasurementType_BOARD_TEMPERATURE_CURRENT = 21,
    SKFChina_Common_MeasurementType_BOARD_TEMPERATURE_MAX = 22,
    SKFChina_Common_MeasurementType_BOARD_TEMPERATURE_MIN = 23,
    SKFChina_Common_MeasurementType_BOARD_TEMPERATURE_HISTORY = 24,
    /* Board humidity */
    SKFChina_Common_MeasurementType_BOARD_HUMIDITY_CURRENT = 25,
    SKFChina_Common_MeasurementType_BOARD_HUMIDITY_MAX = 26,
    SKFChina_Common_MeasurementType_BOARD_HUMIDITY_MIN = 27,
    SKFChina_Common_MeasurementType_BOARD_HUMIDITY_HISTORY = 28,
    /* Battery */
    SKFChina_Common_MeasurementType_VOLTAGE_CURRENT = 29,
    SKFChina_Common_MeasurementType_REMAINING_VOLUME = 30, /* namely RSOC (relative state-of-charge) */
    SKFChina_Common_MeasurementType_STATE_OF_HEALTH_CURRENT = 37,
    SKFChina_Common_MeasurementType_AVERAGE_TIME_TO_FULL = 38,
    SKFChina_Common_MeasurementType_AVERAGE_TIME_TO_EMPTY = 39,
    SKFChina_Common_MeasurementType_BATTERY_SURFACE_TEMPERATURE_CURRENT = 40,
    SKFChina_Common_MeasurementType_BATTERY_MNGMENT_IC_TEMPERATURE_CURRENT = 41,
    /* Communication */
    SKFChina_Common_MeasurementType_CELLULAR_RSRP_CURRENT = 32,
    SKFChina_Common_MeasurementType_CELLULAR_RSRQ_CURRENT = 33,
    SKFChina_Common_MeasurementType_CELLULAR_SINR_CURRENT = 34,
    SKFChina_Common_MeasurementType_CELLULAR_RSSI_CURRENT = 35,
    SKFChina_Common_MeasurementType_NB_IOT_CELEVEL_CURRENT = 36,
    SKFChina_Common_MeasurementType_BLE_RSSI_CURRENT = 42,
    /* Advanced algorithm */
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_MACHINE_RUN_CODE = 43,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_MACHINE_CONDITON_CODE = 44,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ALARM_CODE = 45,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_RMS_MAG_PRE = 46,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_RMS_VIB_PRE = 47,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_EST_RPM_START = 48,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_EST_RPM_END = 49,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_VEL_OV = 50,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_VEL_RSH = 51,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_VEL_MTR = 52,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_VEL_FAN = 53,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_VEL_PUMP = 54,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ENV_OV = 55,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ENV_BPFI = 56,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ENV_BPFO = 57,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ENV_BSF = 58,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ENV_FTF = 59,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ENV_RSH = 60,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ACC_OV = 61,
    SKFChina_Common_MeasurementType_ADVANCED_ALGO_ACC_GEAR = 62
} SKFChina_Common_MeasurementType;

typedef enum _SKFChina_Common_Dimension {
    /* Mask
 0, 1, 2, 4 used */
    SKFChina_Common_Dimension_UNKNOWN_DIMENSION = 0,
    SKFChina_Common_Dimension_DIMENSION_X = 1, /* e.g., roll */
    SKFChina_Common_Dimension_DIMENSION_Y = 2, /* e.g., pitch */
    SKFChina_Common_Dimension_DIMENSION_Z = 4 /* e.g., yaw */
} SKFChina_Common_Dimension;

/* The alarm events */
typedef enum _SKFChina_Common_AlarmAndNotify {
    /* 0 - 8 used */
    SKFChina_Common_AlarmAndNotify_UNKNOWN_ALARM_EVENT = 0,
    /* Alarm for temperature is higher than TEMPERATURE_ALARM_THRESHOLD_CDGREE */
    SKFChina_Common_AlarmAndNotify_TEMPERATURE_HIGH_ALARM_EVENT = 1,
    /* Alarm for relative humidity is higher than HUMIDITY_ALARM_THRESHOLD_PERCENTAGE */
    SKFChina_Common_AlarmAndNotify_HUMIDITY_HIGH_ALARM_EVENT = 2,
    /* Alarm for acceleration in X direction is higher than ACC_SENSOR_ALARM_X_THRESHOLD_G */
    SKFChina_Common_AlarmAndNotify_ACC_X_HIGH_ALARM_EVENT = 3,
    /* Alarm for acceleration in Y direction is higher than ACC_SENSOR_ALARM_Y_THRESHOLD_G */
    SKFChina_Common_AlarmAndNotify_ACC_Y_HIGH_ALARM_EVENT = 4,
    /* Alarm for acceleration in Z direction is higher than ACC_SENSOR_ALARM_Z_THRESHOLD_G */
    SKFChina_Common_AlarmAndNotify_ACC_Z_HIGH_ALARM_EVENT = 5,
    /* Alarm for remaining battery capacity is lower than BATTERY_LOW_ALARM_THRESHOLD_PERCENTAGE */
    SKFChina_Common_AlarmAndNotify_BATTERY_LOW_ALARM_EVENT = 6,
    /* Alarm for anomaly detected */
    SKFChina_Common_AlarmAndNotify_BEARING_ANOMALY_EVENT = 7,
    /* Notification for remaining battery capacity is full
 (i.e., higher than than BATTERY_FULL_NOTIFY_THRESHOLD_PERCENTAGE) */
    SKFChina_Common_AlarmAndNotify_BATTERY_FULL_NOTIFY_EVENT = 8
} SKFChina_Common_AlarmAndNotify;

/* Sensor: the hardware type */
typedef enum _SKFChina_Common_SensorType {
    /* 0 - 12 used */
    SKFChina_Common_SensorType_UNKNOWN_SENSOR = 0,
    SKFChina_Common_SensorType_LIS2DW_VIBRATION = 1,
    SKFChina_Common_SensorType_AD22122_VIBRATION = 2,
    SKFChina_Common_SensorType_IIM4235X_VIBRATION = 9,
    SKFChina_Common_SensorType_TMP1075_TEMPERATURE = 3,
    SKFChina_Common_SensorType_NTC_TEMPERATURE = 11,
    SKFChina_Common_SensorType_SHT40_HUMIDITY_TEMPERATURE = 4,
    SKFChina_Common_SensorType_BQ34210_BATTERY = 5,
    SKFChina_Common_SensorType_EC600_CELLULAR = 6,
    SKFChina_Common_SensorType_EFR32BG24_2_4GHZ_RADIO = 7,
    SKFChina_Common_SensorType_NRF52_2_4GHZ_RADIO = 8,
    SKFChina_Common_SensorType_MMC56X3_MAG = 10,
    SKFChina_Common_SensorType_ADXL382_VIBRATION = 12 /* TODO: Add sensor */
} SKFChina_Common_SensorType;

/* Hardware type: 
 chip information ("C") + platform information ("P") */
typedef enum _SKFChina_Common_HardwareType {
    /* 0 - 5 used */
    SKFChina_Common_HardwareType_UNKNOWN_HARDWARE = 0,
    SKFChina_Common_HardwareType_C_NRF52840_P_DEVKIT = 1,
    SKFChina_Common_HardwareType_C_EFR32BG24_P_INSIGHTMETRO = 2,
    SKFChina_Common_HardwareType_C_BCM2711_P_HIL_NODE = 3,
    SKFChina_Common_HardwareType_C_NRF52840_P_BULLETNODE = 4,
    SKFChina_Common_HardwareType_C_AM6231_P_BULLETGW = 5,
    SKFChina_Common_HardwareType_C_NRF52840_P_BULLETNODEPRO = 6,
    SKFChina_Common_HardwareType_C_AM6231_P_BULLETGWPRO = 7 /* TODO: Add hardware platform */
} SKFChina_Common_HardwareType;

/* Product type */
typedef enum _SKFChina_Common_ProductType {
    /* 0 - 9 used */
    SKFChina_Common_ProductType_UNKNOWN_PRODUCT = 0,
    /* name of INSIGHTMETRO: "INSIGHTMETRO" */
    SKFChina_Common_ProductType_INSIGHTMETRO = 1,
    /* name of IMX_1_NB: "IMX_1_NB" */
    SKFChina_Common_ProductType_IMX_1_NB = 2,
    /* name of IMX_1_NB_PRO: "IMX_1_NB_PRO" */
    SKFChina_Common_ProductType_IMX_1_NB_PRO = 3,
    /* name of HIL_NODE: "HIL_NODE" */
    SKFChina_Common_ProductType_HIL_NODE = 4,
    /* name of BULLET_NODE: "BULLET_NODE" */
    SKFChina_Common_ProductType_BULLET_NODE = 5,
    /* name of BULLET_GATEWAY: "BULLET_GATEWAY" */
    SKFChina_Common_ProductType_BULLET_GATEWAY = 6,
    /* name of INSIGHT_T: "INSIGHT_T" */
    SKFChina_Common_ProductType_INSIGHT_T = 7,
    /* name of BULLET_NODE_PRO: "BULLET_NODE_PRO" */
    SKFChina_Common_ProductType_BULLET_NODE_PRO = 8,
    /* name of BULLET_GATEWAY_PRO: "BULLET_GATEWAY_PRO" */
    SKFChina_Common_ProductType_BULLET_GATEWAY_PRO = 9 /* TODO: Add product */
} SKFChina_Common_ProductType;

/* Unit: the unit of the uploading data */
typedef enum _SKFChina_Common_Unit {
    /* 0 - 23 used */
    SKFChina_Common_Unit_UNKNOWN_UNIT = 0,
    /* Acceleration */
    SKFChina_Common_Unit_MPERS2 = 1, /* m/s2 */
    SKFChina_Common_Unit_GEE = 2, /* g */
    /* Temperature */
    SKFChina_Common_Unit_FDEGREE = 3, /* Fahrenheit */
    SKFChina_Common_Unit_CDEGREE = 4, /* Celsius */
    /* Voltage */
    SKFChina_Common_Unit_VOLT = 5, /* V */
    SKFChina_Common_Unit_MILLIVOLT = 15, /* mV */
    /* Energy and power */
    SKFChina_Common_Unit_COULOMB = 6, /* Coulomb */
    SKFChina_Common_Unit_JOULE = 7, /* Joule */
    SKFChina_Common_Unit_MAH = 8, /* Milliamp hours */
    /* Speed and frequency */
    SKFChina_Common_Unit_KMPERH = 11, /* km/h */
    SKFChina_Common_Unit_MPERS = 12, /* m/s */
    SKFChina_Common_Unit_RPM = 13, /* rpm */
    SKFChina_Common_Unit_HZ = 14, /* Hz */
    /* Velocity */
    SKFChina_Common_Unit_MMPERS = 23, /* mm/s */
    /* Time */
    SKFChina_Common_Unit_TIME_SECOND = 16,
    SKFChina_Common_Unit_TIME_MINUTE = 17,
    SKFChina_Common_Unit_TIME_HOUR = 18,
    SKFChina_Common_Unit_TIME_MILLISECOND = 19,
    /* Ratio */
    SKFChina_Common_Unit_DB = 20,
    SKFChina_Common_Unit_DBM = 21,
    /* Communication */
    SKFChina_Common_Unit_KBPS = 22, /* kbps */
    /* Others */
    SKFChina_Common_Unit_NOUNIT = 9, /* No unit, e.g., the reading from an ADC */
    SKFChina_Common_Unit_PERCENTAGE = 10 /* For relative values, e.g., relative humidity */
} SKFChina_Common_Unit;

/* Range: the range of sensor
 So far, only range of accelerometer is enumerated. */
typedef enum _SKFChina_Common_Range {
    /* 0 - 6, 15, 30, 60 used */
    SKFChina_Common_Range_UNKNOWN_RANGE = 0,
    SKFChina_Common_Range_RANGE_2G = 1, /* +-2 G */
    SKFChina_Common_Range_RANGE_4G = 2, /* +-4 G */
    SKFChina_Common_Range_RANGE_8G = 3, /* +-8 G */
    SKFChina_Common_Range_RANGE_16G = 4, /* +-16 G */
    SKFChina_Common_Range_RANGE_32G = 5, /* +-32 G */
    SKFChina_Common_Range_RANGE_64G = 6, /* +-64 G */
    SKFChina_Common_Range_RANGE_15G = 15, /* +-15 G */
    SKFChina_Common_Range_RANGE_30G = 30, /* +-30 G */
    SKFChina_Common_Range_RANGE_60G = 60 /* +-60 G */
} SKFChina_Common_Range;

/* Format: the format of the (before encoded and after decoded) data (e.g., uint16_t or float32_t)
 Here the endianess should be assigned.
 Given a value 0xaabbccdd, for little endian, memory from low address to high is 0xdd 0xcc 0xbb 0xaa
 for big endian, memory from low address to high is 0xaa 0xbb 0xcc 0xdd */
typedef enum _SKFChina_Common_Format {
    /* 0 - 8 used */
    SKFChina_Common_Format_UNKNOWN_FORMAT = 0,
    /* Integers */
    SKFChina_Common_Format_FORMAT_UINT16 = 1, /* uint16_t, unsigned, bit width 2 bytes */
    SKFChina_Common_Format_FORMAT_INT16 = 2, /* int16_t, signed, bit width 2 bytes */
    SKFChina_Common_Format_FORMAT_UINT32 = 3, /* uint32_t, unsigned, bit width 4 bytes */
    SKFChina_Common_Format_FORMAT_INT32 = 4, /* int32_t, signed, bit width 4 bytes */
    SKFChina_Common_Format_FORMAT_UINT8 = 5, /* uint8_t, unsigned, bit width 1 byte */
    SKFChina_Common_Format_FORMAT_INT8 = 6, /* int8_t, signed, bit width 1 byte */
    /* Values with decimal fractions */
    SKFChina_Common_Format_FORMAT_FLOAT32 = 7, /* float32_t, signed, bit width 4 bytes */
    SKFChina_Common_Format_FORMAT_DOUBLE64 = 8 /* double64_t, signed, bit width 8 bytes */
} SKFChina_Common_Format;

/* Encryption: what encryption is adopted for the @p Data.data */
typedef enum _SKFChina_Common_Encryption {
    /* 0 - 1 used */
    SKFChina_Common_Encryption_UNKNOWN_ENCRYPTION = 0,
    SKFChina_Common_Encryption_NO_ENCRYPTION = 1 /* TODO: Add encryption manner */
} SKFChina_Common_Encryption;

/* Communication type */
typedef enum _SKFChina_Common_CommunicationType {
    /* 0 - 5 used */
    SKFChina_Common_CommunicationType_UNKNOWN_COMM = 0,
    SKFChina_Common_CommunicationType_BLECONNECTION_COMM = 1,
    SKFChina_Common_CommunicationType_BLEMESH_COMM = 2,
    SKFChina_Common_CommunicationType_LTE_COMM = 3,
    SKFChina_Common_CommunicationType_NBIOT_COMM = 4,
    SKFChina_Common_CommunicationType_THREAD_COMM = 5 /* TODO: Add communication */
} SKFChina_Common_CommunicationType;

/* Communication type */
typedef enum _SKFChina_Common_FUOTAType {
    /* 0 - 2 used */
    SKFChina_Common_FUOTAType_UNKNOWN_FUOTATYPE = 0,
    SKFChina_Common_FUOTAType_DIFF = 1,
    SKFChina_Common_FUOTAType_WHOLE = 2
} SKFChina_Common_FUOTAType;

/* File type */
typedef enum _SKFChina_Common_FileType {
    /* 0 - 5 used */
    SKFChina_Common_FileType_UNKNOWN_FILE = 0,
    SKFChina_Common_FileType_CERT_FILE = 1,
    SKFChina_Common_FileType_GATEWAY_CONFIG_FILE = 2,
    SKFChina_Common_FileType_SENSOR_CONFIG_FILE = 3,
    SKFChina_Common_FileType_FUOTA_FILE_MCU_BOOT = 4, /* The file to be updated used by MCU Boot */
    SKFChina_Common_FileType_FUOTA_FILE_RAW = 5 /* Raw .bin file to be updated */
} SKFChina_Common_FileType;

/* The fScheduler configuration item of sensor */
typedef enum _SKFChina_Common_fSchedulerConfigItem { /* 0 - 6 used */
    /* fScheduler
 At least M sets of valid data required over N days */
    SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_M = 0, /* The expected items of data every N days */
    SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_N = 1, /* The period (in day). */
    /* (no time zone, UTC+0, cloud guarantees second must be zero): The start
 of the period. (Default 2022-07-15 00:00:00 UTC+0) */
    SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_NSTARTMOMENT = 2,
    /* Next 10 wake-up (to sense) moments. Follow the last update if failed 
 to update the WS-Array. Follow the built-in rule if nothing is valid 
 in the WS-Array. The built-in rule is to wake up (to sense) according
 to the preset WS moment if M items of data in N days are not met. 
 (Default null) */
    SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_WSARRAY = 3, /* (no time zone, UTC+0) */
    /* To mark the MUSTwake-up moments restored in WS-Array. (Default null) */
    SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_WSSTAR_ARRAY = 4, /* (no time zone, UTC+0) */
    /* To describe the sensing attribute (e.g., sample rate, sample duration,
 etc.) corresponding to WSArray. This array is application-dependent. */
    SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_WSDESC_ARRAY = 5,
    /* Next 5 wake-up (to communicate) moments. Follow the last update if 
 failed to update the WC-Array; otherwise, the preset WC moment is
 applied. (Default null) (MAX interval: 3 days) */
    SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_WCARRAY = 6 /* (no time zone, UTC+0) */
} SKFChina_Common_fSchedulerConfigItem;

/* The configuration item of sensor */
typedef enum _SKFChina_Common_SpecificConfigItem {
    /* 0 - 12, 20 - 132 used */
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_SAMPLE_RATE_HZ = 0,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_X_ENABLE = 1,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_Y_ENABLE = 2,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_Z_ENABLE = 3,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_AXIS = 49,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_RANGE_G = 4,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_ALARM_X_THRESHOLD_G = 6,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_ALARM_Y_THRESHOLD_G = 7,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_ALARM_Z_THRESHOLD_G = 8,
    SKFChina_Common_SpecificConfigItem_ACC_SENSOR_SAMPLE_PTS = 20,
    SKFChina_Common_SpecificConfigItem_TEMPERATURE_SAMPLE_PERIOD_S = 9,
    SKFChina_Common_SpecificConfigItem_TEMPERATURE_ALARM_THRESHOLD_CDGREE = 10,
    SKFChina_Common_SpecificConfigItem_TEMPERATURE_SENSOR_ENABLE = 21,
    SKFChina_Common_SpecificConfigItem_TEMPERATURE_RESOLUTION_CDGREE = 132,
    SKFChina_Common_SpecificConfigItem_HUMIDITY_SAMPLE_PERIOD_S = 11,
    SKFChina_Common_SpecificConfigItem_HUMIDITY_ALARM_THRESHOLD_PERCENTAGE = 12,
    SKFChina_Common_SpecificConfigItem_HUMIDITY_SENSOR_ENABLE = 22,
    SKFChina_Common_SpecificConfigItem_SPEED_TRIGGER_HZ = 23,
    SKFChina_Common_SpecificConfigItem_DIAMETER_WHEEL_CM = 24,
    SKFChina_Common_SpecificConfigItem_BORE_DIAMETER_MM = 85,
    SKFChina_Common_SpecificConfigItem_BATTERY_LOW_ALARM_THRESHOLD_PERCENTAGE = 25,
    SKFChina_Common_SpecificConfigItem_BATTERY_FULL_NOTIFY_THRESHOLD_PERCENTAGE = 26,
    SKFChina_Common_SpecificConfigItem_CLOUD_BACKEND_URL = 27,
    SKFChina_Common_SpecificConfigItem_CLOUD_BACKEND_PORT = 28,
    SKFChina_Common_SpecificConfigItem_CLOUD_BACKEND_MQTT_USERNAME = 110,
    SKFChina_Common_SpecificConfigItem_CLOUD_BACKEND_MQTT_PASSWORD = 111,
    SKFChina_Common_SpecificConfigItem_NTP_SERVER_SETTING = 115,
    SKFChina_Common_SpecificConfigItem_NTP_SERVER_URL = 116,
    SKFChina_Common_SpecificConfigItem_CLOUD_BACKEND_MQTT_SECURITY_TYPE = 117,
    SKFChina_Common_SpecificConfigItem_CLOUD_BACKEND_MQTT_URL = 118,
    SKFChina_Common_SpecificConfigItem_CLOUD_BACKEND_MQTT_PORT = 119,
    SKFChina_Common_SpecificConfigItem_DHCP_ENABLE = 120,
    SKFChina_Common_SpecificConfigItem_STATIC_IP_ADDR = 121,
    SKFChina_Common_SpecificConfigItem_GATEWAY_IP_ADDR = 122,
    SKFChina_Common_SpecificConfigItem_NETMASK = 123,
    SKFChina_Common_SpecificConfigItem_DNSSERVER_ADDR = 124,
    SKFChina_Common_SpecificConfigItem_WORK_MODE = 29,
    SKFChina_Common_SpecificConfigItem_TX_POWER_BLE_ADV_DBM = 30,
    SKFChina_Common_SpecificConfigItem_TX_POWER_BLE_AUX_ADV_DBM = 31,
    SKFChina_Common_SpecificConfigItem_DATA_RATE_BLE_AUX_ADV_KBPS = 32, /* kbps */
    SKFChina_Common_SpecificConfigItem_TX_POWER_BLE_CONN_DBM = 33,
    SKFChina_Common_SpecificConfigItem_DATA_RATE_BLE_CONN_KBPS = 34, /* kbps */
    SKFChina_Common_SpecificConfigItem_CURRENT_TIME = 35,
    SKFChina_Common_SpecificConfigItem_LATEST_CONFIG_TIME = 112,
    SKFChina_Common_SpecificConfigItem_GATEWAY_ADDR = 36,
    SKFChina_Common_SpecificConfigItem_QUICKPOLLING_PERIOD_S = 37,
    SKFChina_Common_SpecificConfigItem_REGULARSENSING_PERIOD_S = 38,
    SKFChina_Common_SpecificConfigItem_COMMUNICATION_PERIOD_S = 39,
    SKFChina_Common_SpecificConfigItem_QUICKPOLLING_REF_STARTTIME_S = 40,
    SKFChina_Common_SpecificConfigItem_REGULARSENSING_REF_STARTTIME_S = 41,
    SKFChina_Common_SpecificConfigItem_COMMUNICATION_REF_STARTTIME_S = 42,
    SKFChina_Common_SpecificConfigItem_WAVEDATA_ACQ_PERIOD_S = 113,
    SKFChina_Common_SpecificConfigItem_WAVEDATA_ACQ_REF_STARTTIME_S = 114,
    SKFChina_Common_SpecificConfigItem_PRE_ACQ_VIB_FS_HZ = 43,
    SKFChina_Common_SpecificConfigItem_PRE_ACQ_VIB_N = 44,
    SKFChina_Common_SpecificConfigItem_PRE_ACQ_VIB_AXIS_ACQ_EVAL = 45,
    SKFChina_Common_SpecificConfigItem_PRE_ACQ_VIB_RANGE = 46,
    SKFChina_Common_SpecificConfigItem_PRE_ACQ_MAG_FS_HZ = 47,
    SKFChina_Common_SpecificConfigItem_PRE_ACQ_MAG_N = 48,
    SKFChina_Common_SpecificConfigItem_PRE_ACQ_MAG_AXIS_ACQ_EVAL = 50,
    SKFChina_Common_SpecificConfigItem_ACQ_MAG_FS_HZ = 51,
    SKFChina_Common_SpecificConfigItem_ACQ_MAG_N = 52,
    SKFChina_Common_SpecificConfigItem_ACQ_MAG_AXIS_ACQ_EVAL = 53,
    SKFChina_Common_SpecificConfigItem_FS_COEF = 54,
    SKFChina_Common_SpecificConfigItem_GEE_COEF = 55,
    SKFChina_Common_SpecificConfigItem_V_COEF = 56,
    SKFChina_Common_SpecificConfigItem_MEAS_POSITION = 57,
    SKFChina_Common_SpecificConfigItem_MEAS_LOAD = 58,
    SKFChina_Common_SpecificConfigItem_MEAS_AXIS_VIB = 59,
    SKFChina_Common_SpecificConfigItem_MEAS_AXIS_MAG = 60,
    SKFChina_Common_SpecificConfigItem_VIB_START_FG = 61,
    SKFChina_Common_SpecificConfigItem_VIB_RMS_START_TL = 62,
    SKFChina_Common_SpecificConfigItem_MAG_START_FG = 63,
    SKFChina_Common_SpecificConfigItem_MAG_RMS_START_TL = 64,
    SKFChina_Common_SpecificConfigItem_MAG_STABLE_FG = 65,
    SKFChina_Common_SpecificConfigItem_MAG_RMS_VAR_TH = 66,
    SKFChina_Common_SpecificConfigItem_RPM_VAR_RANGE = 67,
    SKFChina_Common_SpecificConfigItem_DEC_LOGIC_TEMP_M = 68,
    SKFChina_Common_SpecificConfigItem_DEC_LOGIC_TEMP_N = 69,
    SKFChina_Common_SpecificConfigItem_DEC_LOGIC_LEARN_NUM_TEMP = 70,
    SKFChina_Common_SpecificConfigItem_DEC_LOGIC_VIB_M = 71,
    SKFChina_Common_SpecificConfigItem_DEC_LOGIC_VIB_N = 72,
    SKFChina_Common_SpecificConfigItem_DEC_LOGIC_LEARN_NUM_VIB = 73,
    SKFChina_Common_SpecificConfigItem_DEC_LOGIC_LEARN_NUM_MAG = 74,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_TEMP = 75,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_OV = 76,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_MECH = 77,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_BRG = 78,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_LUB = 79,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_MTR = 80,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_GEAR = 81,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_FAN = 82,
    SKFChina_Common_SpecificConfigItem_FUNC_ANOM_PUMP = 83,
    SKFChina_Common_SpecificConfigItem_ASSET_LEVEL = 84,
    SKFChina_Common_SpecificConfigItem_FLEX_TYPE = 86,
    SKFChina_Common_SpecificConfigItem_RUN_SPEED_RPM = 87,
    SKFChina_Common_SpecificConfigItem_BRG_INFO_BPFO = 88,
    SKFChina_Common_SpecificConfigItem_BRG_INFO_BPFI = 89,
    SKFChina_Common_SpecificConfigItem_BRG_INFO_BSF = 90,
    SKFChina_Common_SpecificConfigItem_BRG_INFO_FTF = 91,
    SKFChina_Common_SpecificConfigItem_MTR_INFO_FL = 92,
    SKFChina_Common_SpecificConfigItem_MTR_INFO_BAR = 93,
    SKFChina_Common_SpecificConfigItem_GEAR_INFO_TOOTH = 94,
    SKFChina_Common_SpecificConfigItem_FAN_INFO_BLADE = 95,
    SKFChina_Common_SpecificConfigItem_PUMP_INFO_VANE = 96,
    SKFChina_Common_SpecificConfigItem_TEMP_OV_ALERT_CDEGREE = 97,
    SKFChina_Common_SpecificConfigItem_ACC_OV_ALERT = 98,
    SKFChina_Common_SpecificConfigItem_ACC_OV_ALARM = 99,
    SKFChina_Common_SpecificConfigItem_ACC_HAL_ALERT = 100,
    SKFChina_Common_SpecificConfigItem_ACC_HAL_ALARM = 101,
    SKFChina_Common_SpecificConfigItem_VEL_OV_ALERT = 102,
    SKFChina_Common_SpecificConfigItem_VEL_OV_ALARM = 103,
    SKFChina_Common_SpecificConfigItem_VEL_HAL_ALERT = 104,
    SKFChina_Common_SpecificConfigItem_VEL_HAL_ALARM = 105,
    SKFChina_Common_SpecificConfigItem_ENV_OV_ALERT = 106,
    SKFChina_Common_SpecificConfigItem_ENV_OV_ALARM = 107,
    SKFChina_Common_SpecificConfigItem_ENV_HAL_ALERT = 108,
    SKFChina_Common_SpecificConfigItem_ENV_HAL_ALARM = 109,
    SKFChina_Common_SpecificConfigItem_BAUDRATE_SLAVE = 125,
    SKFChina_Common_SpecificConfigItem_ADDR_SLAVE = 126,
    SKFChina_Common_SpecificConfigItem_PARITY_SLAVE = 127,
    SKFChina_Common_SpecificConfigItem_STOP_SLAVE = 128,
    SKFChina_Common_SpecificConfigItem_REGISTER_MODE = 129,
    SKFChina_Common_SpecificConfigItem_DESCRIPTION = 131,
    SKFChina_Common_SpecificConfigItem_CHILDREN = 130
} SKFChina_Common_SpecificConfigItem;

typedef enum _SKFChina_Common_CloudBackendMqttSecType {
    /* 0 - 3 used */
    SKFChina_Common_CloudBackendMqttSecType_MQTT_SEC_TYPE_NO_SECURITY = 0, /* 0: no security for debug */
    SKFChina_Common_CloudBackendMqttSecType_MQTT_SEC_TYPE_USER_AND_PSW = 1, /* 1: username and password */
    SKFChina_Common_CloudBackendMqttSecType_MQTT_SEC_TYPE_TLS = 2, /* 2: TLS */
    SKFChina_Common_CloudBackendMqttSecType_MQTT_SEC_TYPE_USER_AND_PSW_TLS = 3 /* 3: username and password with TLS */
} SKFChina_Common_CloudBackendMqttSecType;

/* The work mode of sensor */
typedef enum _SKFChina_Common_WorkMode {
    /* 0 - 4 used */
    SKFChina_Common_WorkMode_FLIGHT_MODE = 0,
    SKFChina_Common_WorkMode_STANDBY_MODE = 1,
    SKFChina_Common_WorkMode_NORMAL_MODE = 2,
    SKFChina_Common_WorkMode_FCT_MODE = 3,
    SKFChina_Common_WorkMode_FLIGHT_FACTORY_RESET_MODE = 4
} SKFChina_Common_WorkMode;

/* The configuration item of sensor */
typedef enum _SKFChina_Common_Command {
    /* 0 - 7 used */
    SKFChina_Common_Command_IMMEDIATE_TEMPERATURE_MEASUREMENT = 0,
    SKFChina_Common_Command_IMMEDIATE_VIBRATION_MEASUREMENT = 1,
    SKFChina_Common_Command_IMMEDIATE_QUICK_LED_BLINK = 2,
    SKFChina_Common_Command_IMMEDIATE_SLOW_LED_BLINK = 3,
    SKFChina_Common_Command_IMMEDIATE_REGULAR_MEASUREMENT = 4,
    SKFChina_Common_Command_CLEAR_TEMPERATURE_HISTORY = 5,
    SKFChina_Common_Command_SET_REMAINING_BATTERY_VOLUME = 6,
    SKFChina_Common_Command_CLOSE_SESSION = 7
} SKFChina_Common_Command;

/* Measurement description (for fScheduler)
 Deprecated. */
typedef enum _SKFChina_Common_Wsdesc {
    /* 0 used */
    SKFChina_Common_Wsdesc_NORMAL_MEASUREMENT = 0 /* TODO: add the description */
} SKFChina_Common_Wsdesc;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SKFChina_Common_MeasurementType_MIN SKFChina_Common_MeasurementType_UNKNOWN_MEASUREMENT_TYPE
#define _SKFChina_Common_MeasurementType_MAX SKFChina_Common_MeasurementType_VIBRATION_ACC_STATUS_WAVE
#define _SKFChina_Common_MeasurementType_ARRAYSIZE ((SKFChina_Common_MeasurementType)(SKFChina_Common_MeasurementType_VIBRATION_ACC_STATUS_WAVE+1))

#define _SKFChina_Common_Dimension_MIN SKFChina_Common_Dimension_UNKNOWN_DIMENSION
#define _SKFChina_Common_Dimension_MAX SKFChina_Common_Dimension_DIMENSION_Z
#define _SKFChina_Common_Dimension_ARRAYSIZE ((SKFChina_Common_Dimension)(SKFChina_Common_Dimension_DIMENSION_Z+1))

#define _SKFChina_Common_AlarmAndNotify_MIN SKFChina_Common_AlarmAndNotify_UNKNOWN_ALARM_EVENT
#define _SKFChina_Common_AlarmAndNotify_MAX SKFChina_Common_AlarmAndNotify_BATTERY_FULL_NOTIFY_EVENT
#define _SKFChina_Common_AlarmAndNotify_ARRAYSIZE ((SKFChina_Common_AlarmAndNotify)(SKFChina_Common_AlarmAndNotify_BATTERY_FULL_NOTIFY_EVENT+1))

#define _SKFChina_Common_SensorType_MIN SKFChina_Common_SensorType_UNKNOWN_SENSOR
#define _SKFChina_Common_SensorType_MAX SKFChina_Common_SensorType_ADXL382_VIBRATION
#define _SKFChina_Common_SensorType_ARRAYSIZE ((SKFChina_Common_SensorType)(SKFChina_Common_SensorType_ADXL382_VIBRATION+1))

#define _SKFChina_Common_HardwareType_MIN SKFChina_Common_HardwareType_UNKNOWN_HARDWARE
#define _SKFChina_Common_HardwareType_MAX SKFChina_Common_HardwareType_C_AM6231_P_BULLETGWPRO
#define _SKFChina_Common_HardwareType_ARRAYSIZE ((SKFChina_Common_HardwareType)(SKFChina_Common_HardwareType_C_AM6231_P_BULLETGWPRO+1))

#define _SKFChina_Common_ProductType_MIN SKFChina_Common_ProductType_UNKNOWN_PRODUCT
#define _SKFChina_Common_ProductType_MAX SKFChina_Common_ProductType_BULLET_GATEWAY_PRO
#define _SKFChina_Common_ProductType_ARRAYSIZE ((SKFChina_Common_ProductType)(SKFChina_Common_ProductType_BULLET_GATEWAY_PRO+1))

#define _SKFChina_Common_Unit_MIN SKFChina_Common_Unit_UNKNOWN_UNIT
#define _SKFChina_Common_Unit_MAX SKFChina_Common_Unit_MMPERS
#define _SKFChina_Common_Unit_ARRAYSIZE ((SKFChina_Common_Unit)(SKFChina_Common_Unit_MMPERS+1))

#define _SKFChina_Common_Range_MIN SKFChina_Common_Range_UNKNOWN_RANGE
#define _SKFChina_Common_Range_MAX SKFChina_Common_Range_RANGE_60G
#define _SKFChina_Common_Range_ARRAYSIZE ((SKFChina_Common_Range)(SKFChina_Common_Range_RANGE_60G+1))

#define _SKFChina_Common_Format_MIN SKFChina_Common_Format_UNKNOWN_FORMAT
#define _SKFChina_Common_Format_MAX SKFChina_Common_Format_FORMAT_DOUBLE64
#define _SKFChina_Common_Format_ARRAYSIZE ((SKFChina_Common_Format)(SKFChina_Common_Format_FORMAT_DOUBLE64+1))

#define _SKFChina_Common_Encryption_MIN SKFChina_Common_Encryption_UNKNOWN_ENCRYPTION
#define _SKFChina_Common_Encryption_MAX SKFChina_Common_Encryption_NO_ENCRYPTION
#define _SKFChina_Common_Encryption_ARRAYSIZE ((SKFChina_Common_Encryption)(SKFChina_Common_Encryption_NO_ENCRYPTION+1))

#define _SKFChina_Common_CommunicationType_MIN SKFChina_Common_CommunicationType_UNKNOWN_COMM
#define _SKFChina_Common_CommunicationType_MAX SKFChina_Common_CommunicationType_THREAD_COMM
#define _SKFChina_Common_CommunicationType_ARRAYSIZE ((SKFChina_Common_CommunicationType)(SKFChina_Common_CommunicationType_THREAD_COMM+1))

#define _SKFChina_Common_FUOTAType_MIN SKFChina_Common_FUOTAType_UNKNOWN_FUOTATYPE
#define _SKFChina_Common_FUOTAType_MAX SKFChina_Common_FUOTAType_WHOLE
#define _SKFChina_Common_FUOTAType_ARRAYSIZE ((SKFChina_Common_FUOTAType)(SKFChina_Common_FUOTAType_WHOLE+1))

#define _SKFChina_Common_FileType_MIN SKFChina_Common_FileType_UNKNOWN_FILE
#define _SKFChina_Common_FileType_MAX SKFChina_Common_FileType_FUOTA_FILE_RAW
#define _SKFChina_Common_FileType_ARRAYSIZE ((SKFChina_Common_FileType)(SKFChina_Common_FileType_FUOTA_FILE_RAW+1))

#define _SKFChina_Common_fSchedulerConfigItem_MIN SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_M
#define _SKFChina_Common_fSchedulerConfigItem_MAX SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_WCARRAY
#define _SKFChina_Common_fSchedulerConfigItem_ARRAYSIZE ((SKFChina_Common_fSchedulerConfigItem)(SKFChina_Common_fSchedulerConfigItem_FSCHEDULER_WCARRAY+1))

#define _SKFChina_Common_SpecificConfigItem_MIN SKFChina_Common_SpecificConfigItem_ACC_SENSOR_SAMPLE_RATE_HZ
#define _SKFChina_Common_SpecificConfigItem_MAX SKFChina_Common_SpecificConfigItem_TEMPERATURE_RESOLUTION_CDGREE
#define _SKFChina_Common_SpecificConfigItem_ARRAYSIZE ((SKFChina_Common_SpecificConfigItem)(SKFChina_Common_SpecificConfigItem_TEMPERATURE_RESOLUTION_CDGREE+1))

#define _SKFChina_Common_CloudBackendMqttSecType_MIN SKFChina_Common_CloudBackendMqttSecType_MQTT_SEC_TYPE_NO_SECURITY
#define _SKFChina_Common_CloudBackendMqttSecType_MAX SKFChina_Common_CloudBackendMqttSecType_MQTT_SEC_TYPE_USER_AND_PSW_TLS
#define _SKFChina_Common_CloudBackendMqttSecType_ARRAYSIZE ((SKFChina_Common_CloudBackendMqttSecType)(SKFChina_Common_CloudBackendMqttSecType_MQTT_SEC_TYPE_USER_AND_PSW_TLS+1))

#define _SKFChina_Common_WorkMode_MIN SKFChina_Common_WorkMode_FLIGHT_MODE
#define _SKFChina_Common_WorkMode_MAX SKFChina_Common_WorkMode_FLIGHT_FACTORY_RESET_MODE
#define _SKFChina_Common_WorkMode_ARRAYSIZE ((SKFChina_Common_WorkMode)(SKFChina_Common_WorkMode_FLIGHT_FACTORY_RESET_MODE+1))

#define _SKFChina_Common_Command_MIN SKFChina_Common_Command_IMMEDIATE_TEMPERATURE_MEASUREMENT
#define _SKFChina_Common_Command_MAX SKFChina_Common_Command_CLOSE_SESSION
#define _SKFChina_Common_Command_ARRAYSIZE ((SKFChina_Common_Command)(SKFChina_Common_Command_CLOSE_SESSION+1))

#define _SKFChina_Common_Wsdesc_MIN SKFChina_Common_Wsdesc_NORMAL_MEASUREMENT
#define _SKFChina_Common_Wsdesc_MAX SKFChina_Common_Wsdesc_NORMAL_MEASUREMENT
#define _SKFChina_Common_Wsdesc_ARRAYSIZE ((SKFChina_Common_Wsdesc)(SKFChina_Common_Wsdesc_NORMAL_MEASUREMENT+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
