/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SKFCHINA_CONFIGURATIONANDCOMMAND_CONFIGURATIONANDCOMMAND_PB_H_INCLUDED
#define PB_SKFCHINA_CONFIGURATIONANDCOMMAND_CONFIGURATIONANDCOMMAND_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"
#include "Froto.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* What to retrieve */
typedef enum _SKFChina_ConfigurationAndCommand_RetrievePayload {
    /* 0 - 5 used */
    SKFChina_ConfigurationAndCommand_RetrievePayload_UNKNOWN_RETRIEVE = 0,
    SKFChina_ConfigurationAndCommand_RetrievePayload_CURRENT_CONFIG_HASH = 1,
    SKFChina_ConfigurationAndCommand_RetrievePayload_SPECIFIC_CURRENT_CONFIG = 2,
    SKFChina_ConfigurationAndCommand_RetrievePayload_FSCHEDULER_CURRENT_CONFIG = 3,
    SKFChina_ConfigurationAndCommand_RetrievePayload_GATEWAY_CONFIG_FILE_CONFIG = 4,
    SKFChina_ConfigurationAndCommand_RetrievePayload_SENSOR_CONFIG_FILE_CONFIG = 5
} SKFChina_ConfigurationAndCommand_RetrievePayload;

/* Struct definitions */
typedef struct _SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg {
    /* In the current design: field numbers 1 has been used. */
    SKFChina_Common_SpecificConfigItem specific_config_item;
} SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg;

typedef struct _SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg {
    /* In the current design: field numbers 1 has been used. */
    SKFChina_Common_fSchedulerConfigItem fscheduler_config_item;
} SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg;

/* To retrieve the current configuration */
typedef struct _SKFChina_ConfigurationAndCommand_ConfigRetrieve { /* In the current design: field numbers 1 - 10 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    SKFChina_ConfigurationAndCommand_RetrievePayload payload;
    /* Only required when @p payload is SPECIFIC_CURRENT_CONFIG */
    pb_callback_t specific_config_item;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
    /* Only required when @p payload is FSCHEDULER_CURRENT_CONFIG */
    pb_callback_t fscheduler_config_item;
    /* Memory ID */
    bool has_memory_id;
    int32_t memory_id;
    /* The HTTP POST address */
    pb_callback_t httpPostUrl;
    /* The corresponding name id of the sensor */
    bool has_name_id;
    uint32_t name_id;
} SKFChina_ConfigurationAndCommand_ConfigRetrieve;

/* The retrieve reply for @p SPECIFIC_CURRENT_CONFIG
 If the retrived configuration items are too much, only first retrieved items (which can be contained in
 a packet) can be replied. */
typedef struct _SKFChina_ConfigurationAndCommand_SpecificConfigUpload { /* In the current design: field numbers 1 - 6 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The type of product */
    SKFChina_Common_ProductType product;
    /* Configuration pair */
    pb_callback_t config_pair;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_ConfigurationAndCommand_SpecificConfigUpload;

typedef struct _SKFChina_ConfigurationAndCommand_TimeArrayElement { /* In the current design: field number 1 has been used. */
    /* Unix timestamp, 0 time zone, unit is ms */
    uint64_t time;
} SKFChina_ConfigurationAndCommand_TimeArrayElement;

/* The retrieve reply for @p CURRENT_CONFIG_HASH or upload directly the current configuration hash */
typedef struct _SKFChina_ConfigurationAndCommand_ConfigHashUpload { /* In the current design: field numbers 1 - 9 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The type of product */
    SKFChina_Common_ProductType product;
    /* hash value of all the configuration items (required by a specific application): elf hash adopted. */
    uint32_t config_hash_value;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
    bool has_last_edit_time;
    SKFChina_ConfigurationAndCommand_TimeArrayElement last_edit_time;
    /* hash value bitmap: corresponding bit setting to "1" indicates the configure item would be calculated
 All item would be calculated if abscent */
    pb_callback_t config_hash_bitmap;
    /* The bitmap length (in bytes)
 All item would be calculated if abscent */
    bool has_config_hash_len_byte;
    uint32_t config_hash_len_byte;
} SKFChina_ConfigurationAndCommand_ConfigHashUpload;

typedef struct _SKFChina_ConfigurationAndCommand_TimeArray {
    /* In the current design: field number 1 has been used. */
    pb_callback_t time;
} SKFChina_ConfigurationAndCommand_TimeArray;

typedef struct _SKFChina_ConfigurationAndCommand_BoolArrayElement {
    /* In the current design: field number 1 has been used. */
    bool YesOrNo;
} SKFChina_ConfigurationAndCommand_BoolArrayElement;

typedef struct _SKFChina_ConfigurationAndCommand_BoolArray {
    /* In the current design: field number 1 has been used. */
    pb_callback_t YesOrNo;
} SKFChina_ConfigurationAndCommand_BoolArray;

typedef struct _SKFChina_ConfigurationAndCommand_WorkModePair {
    /* In the current design: field numbers 1 - 2 have been used. */
    SKFChina_Common_WorkMode work_mode;
    pb_callback_t parameter;
} SKFChina_ConfigurationAndCommand_WorkModePair;

typedef struct _SKFChina_ConfigurationAndCommand_GatewayInfoPair {
    /* In the current design: field numbers 1 - 2 have been used. */
    pb_callback_t mac_address;
    uint32_t name_id;
} SKFChina_ConfigurationAndCommand_GatewayInfoPair;

typedef struct _SKFChina_ConfigurationAndCommand_DescConfigPairMetric {
    /* In the current design: field numbers 2 - 4, 5 - 11 have been used.
 time is used to find the corresponding element in wsarray */
    SKFChina_Common_SpecificConfigItem specific_config_item;
    pb_size_t which_config_content;
    union {
        pb_callback_t general_config_content;
        SKFChina_ConfigurationAndCommand_TimeArray time_config_content;
        SKFChina_ConfigurationAndCommand_BoolArray bool_config_content;
        uint32_t general_config_content_uint32;
        int32_t general_config_content_int32;
        float general_config_content_float;
        bool general_config_content_bool;
    } config_content;
    /* Memory ID */
    bool has_memory_id;
    int32_t memory_id;
} SKFChina_ConfigurationAndCommand_DescConfigPairMetric;

typedef struct _SKFChina_ConfigurationAndCommand_DescConfigPair {
    /* In the current design: field numbers 1 - 2 have been used. */
    uint64_t time;
    pb_callback_t metric;
} SKFChina_ConfigurationAndCommand_DescConfigPair;

typedef struct _SKFChina_ConfigurationAndCommand_MqttSecTypePair {
    /* In the current design: field numbers 1 - 2 have been used. */
    SKFChina_Common_CloudBackendMqttSecType secType;
    pb_callback_t parameter;
} SKFChina_ConfigurationAndCommand_MqttSecTypePair;

typedef struct _SKFChina_ConfigurationAndCommand_IpAddr {
    /* In the current design: field numbers 1 - 2 have been used. */
    bool isIpv4;
    pb_callback_t addr;
} SKFChina_ConfigurationAndCommand_IpAddr;

typedef struct _SKFChina_ConfigurationAndCommand_ChildNode {
    /* In the current design: field numbers 1 - 9 have been used. */
    uint32_t order;
    uint32_t totalChildren;
    pb_callback_t type;
    pb_callback_t manufacturer;
    pb_callback_t name;
    uint32_t nameId;
    pb_callback_t BLESensorName;
    pb_callback_t macAddr;
    pb_callback_t description;
} SKFChina_ConfigurationAndCommand_ChildNode;

typedef struct _SKFChina_ConfigurationAndCommand_ChildrenList { /* In the current design: field number 1 has been used. */
    pb_callback_t child;
} SKFChina_ConfigurationAndCommand_ChildrenList;

/* For fScheduler */
typedef struct _SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc { /* In the current design: field number 1 has been used. */
    /* Description for wake-up-to-sense (for fScheduler) */
    pb_callback_t description;
} SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc;

typedef struct _SKFChina_ConfigurationAndCommand_ConfigPair {
    pb_size_t which_config_item;
    union {
        SKFChina_Common_SpecificConfigItem specific_config_item;
        SKFChina_Common_fSchedulerConfigItem fscheduler_config_item;
    } config_item;
    pb_size_t which_config_content;
    union {
        pb_callback_t general_config_content;
        SKFChina_ConfigurationAndCommand_TimeArray time_config_content;
        SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc measurement_description;
        SKFChina_ConfigurationAndCommand_BoolArray bool_config_content;
        uint32_t general_config_content_uint32;
        int32_t general_config_content_int32;
        float general_config_content_float;
        SKFChina_ConfigurationAndCommand_WorkModePair work_mode_content;
        SKFChina_ConfigurationAndCommand_GatewayInfoPair gateway_info_content;
        bool general_config_content_bool;
        SKFChina_ConfigurationAndCommand_MqttSecTypePair mqtt_sec_type;
        SKFChina_ConfigurationAndCommand_IpAddr ip_addr;
        SKFChina_ConfigurationAndCommand_ChildrenList children_list;
    } config_content;
    bool has_memory_id;
    int32_t memory_id;
} SKFChina_ConfigurationAndCommand_ConfigPair;

/* To disseminate the configuration to sensor */
typedef struct _SKFChina_ConfigurationAndCommand_ConfigDisseminate { /* In the current design: field numbers 1 - 6 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The type of product */
    SKFChina_Common_ProductType product;
    /* Configuration pair */
    pb_callback_t config_pair;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_ConfigurationAndCommand_ConfigDisseminate;

typedef struct _SKFChina_ConfigurationAndCommand_CommandPair { /* In the current design: field numbers 1 - 7 have been used. */
    SKFChina_Common_Command command;
    pb_size_t which_command_para;
    union {
        pb_callback_t general_config_content;
        SKFChina_ConfigurationAndCommand_TimeArray time_config_content;
        SKFChina_ConfigurationAndCommand_BoolArray bool_config_content;
        uint32_t general_config_content_uint32;
        int32_t general_config_content_int32;
        float general_config_content_float;
    } command_para;
} SKFChina_ConfigurationAndCommand_CommandPair;

/* To disseminate the configuration to sensor */
typedef struct _SKFChina_ConfigurationAndCommand_CommandDisseminate { /* In the current design: field numbers 1 - 6 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The type of product */
    SKFChina_Common_ProductType product;
    /* Command pair */
    bool has_command_pair;
    SKFChina_ConfigurationAndCommand_CommandPair command_pair;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_ConfigurationAndCommand_CommandDisseminate;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SKFChina_ConfigurationAndCommand_RetrievePayload_MIN SKFChina_ConfigurationAndCommand_RetrievePayload_UNKNOWN_RETRIEVE
#define _SKFChina_ConfigurationAndCommand_RetrievePayload_MAX SKFChina_ConfigurationAndCommand_RetrievePayload_SENSOR_CONFIG_FILE_CONFIG
#define _SKFChina_ConfigurationAndCommand_RetrievePayload_ARRAYSIZE ((SKFChina_ConfigurationAndCommand_RetrievePayload)(SKFChina_ConfigurationAndCommand_RetrievePayload_SENSOR_CONFIG_FILE_CONFIG+1))

#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_specific_config_item_ENUMTYPE SKFChina_Common_SpecificConfigItem

#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_fscheduler_config_item_ENUMTYPE SKFChina_Common_fSchedulerConfigItem

#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_payload_ENUMTYPE SKFChina_ConfigurationAndCommand_RetrievePayload

#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_product_ENUMTYPE SKFChina_Common_ProductType

#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_product_ENUMTYPE SKFChina_Common_ProductType





#define SKFChina_ConfigurationAndCommand_WorkModePair_work_mode_ENUMTYPE SKFChina_Common_WorkMode


#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_specific_config_item_ENUMTYPE SKFChina_Common_SpecificConfigItem


#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_secType_ENUMTYPE SKFChina_Common_CloudBackendMqttSecType





#define SKFChina_ConfigurationAndCommand_ConfigPair_config_item_specific_config_item_ENUMTYPE SKFChina_Common_SpecificConfigItem
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_item_fscheduler_config_item_ENUMTYPE SKFChina_Common_fSchedulerConfigItem

#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_product_ENUMTYPE SKFChina_Common_ProductType

#define SKFChina_ConfigurationAndCommand_CommandPair_command_ENUMTYPE SKFChina_Common_Command

#define SKFChina_ConfigurationAndCommand_CommandDisseminate_product_ENUMTYPE SKFChina_Common_ProductType


/* Initializer values for message structs */
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_init_default {_SKFChina_Common_SpecificConfigItem_MIN}
#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_init_default {_SKFChina_Common_fSchedulerConfigItem_MIN}
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_ConfigurationAndCommand_RetrievePayload_MIN, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, 0, false, 0, false, SKFChina_ConfigurationAndCommand_TimeArrayElement_init_default, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_TimeArrayElement_init_default {0}
#define SKFChina_ConfigurationAndCommand_TimeArray_init_default {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_BoolArrayElement_init_default {0}
#define SKFChina_ConfigurationAndCommand_BoolArray_init_default {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_WorkModePair_init_default {_SKFChina_Common_WorkMode_MIN, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_init_default {{{NULL}, NULL}, 0}
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_init_default {_SKFChina_Common_SpecificConfigItem_MIN, 0, {{{NULL}, NULL}}, false, 0}
#define SKFChina_ConfigurationAndCommand_DescConfigPair_init_default {0, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_init_default {_SKFChina_Common_CloudBackendMqttSecType_MIN, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_IpAddr_init_default {0, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_ChildNode_init_default {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_ChildrenList_init_default {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_init_default {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_ConfigPair_init_default {0, {_SKFChina_Common_SpecificConfigItem_MIN}, 0, {{{NULL}, NULL}}, false, 0}
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_CommandPair_init_default {_SKFChina_Common_Command_MIN, 0, {{{NULL}, NULL}}}
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, false, SKFChina_ConfigurationAndCommand_CommandPair_init_default, false, 0}
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_init_zero {_SKFChina_Common_SpecificConfigItem_MIN}
#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_init_zero {_SKFChina_Common_fSchedulerConfigItem_MIN}
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_ConfigurationAndCommand_RetrievePayload_MIN, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, 0, false, 0, false, SKFChina_ConfigurationAndCommand_TimeArrayElement_init_zero, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_TimeArrayElement_init_zero {0}
#define SKFChina_ConfigurationAndCommand_TimeArray_init_zero {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_BoolArrayElement_init_zero {0}
#define SKFChina_ConfigurationAndCommand_BoolArray_init_zero {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_WorkModePair_init_zero {_SKFChina_Common_WorkMode_MIN, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_init_zero {{{NULL}, NULL}, 0}
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_init_zero {_SKFChina_Common_SpecificConfigItem_MIN, 0, {{{NULL}, NULL}}, false, 0}
#define SKFChina_ConfigurationAndCommand_DescConfigPair_init_zero {0, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_init_zero {_SKFChina_Common_CloudBackendMqttSecType_MIN, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_IpAddr_init_zero {0, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_ChildNode_init_zero {0, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_ChildrenList_init_zero {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_init_zero {{{NULL}, NULL}}
#define SKFChina_ConfigurationAndCommand_ConfigPair_init_zero {0, {_SKFChina_Common_SpecificConfigItem_MIN}, 0, {{{NULL}, NULL}}, false, 0}
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, {{NULL}, NULL}, false, 0}
#define SKFChina_ConfigurationAndCommand_CommandPair_init_zero {_SKFChina_Common_Command_MIN, 0, {{{NULL}, NULL}}}
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, false, SKFChina_ConfigurationAndCommand_CommandPair_init_zero, false, 0}

/* Field tags (for use in manual encoding/decoding) */
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_specific_config_item_tag 1
#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_fscheduler_config_item_tag 1
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_header_tag 1
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_appVer_tag 2
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_sensor_id_tag 3
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_payload_tag 4
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_specific_config_item_tag 5
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_is_big_endian_tag 6
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_fscheduler_config_item_tag 7
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_memory_id_tag 8
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_httpPostUrl_tag 9
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_name_id_tag 10
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_header_tag 1
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_appVer_tag 2
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_sensor_id_tag 3
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_product_tag 4
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_config_pair_tag 5
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_is_big_endian_tag 6
#define SKFChina_ConfigurationAndCommand_TimeArrayElement_time_tag 1
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_header_tag 1
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_appVer_tag 2
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_sensor_id_tag 3
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_product_tag 4
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_config_hash_value_tag 5
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_is_big_endian_tag 6
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_last_edit_time_tag 7
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_config_hash_bitmap_tag 8
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_config_hash_len_byte_tag 9
#define SKFChina_ConfigurationAndCommand_TimeArray_time_tag 1
#define SKFChina_ConfigurationAndCommand_BoolArrayElement_YesOrNo_tag 1
#define SKFChina_ConfigurationAndCommand_BoolArray_YesOrNo_tag 1
#define SKFChina_ConfigurationAndCommand_WorkModePair_work_mode_tag 1
#define SKFChina_ConfigurationAndCommand_WorkModePair_parameter_tag 2
#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_mac_address_tag 1
#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_name_id_tag 2
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_specific_config_item_tag 2
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_general_config_content_tag 3
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_time_config_content_tag 4
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_bool_config_content_tag 6
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_general_config_content_uint32_tag 7
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_general_config_content_int32_tag 8
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_general_config_content_float_tag 9
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_general_config_content_bool_tag 11
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_memory_id_tag 10
#define SKFChina_ConfigurationAndCommand_DescConfigPair_time_tag 1
#define SKFChina_ConfigurationAndCommand_DescConfigPair_metric_tag 2
#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_secType_tag 1
#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_parameter_tag 2
#define SKFChina_ConfigurationAndCommand_IpAddr_isIpv4_tag 1
#define SKFChina_ConfigurationAndCommand_IpAddr_addr_tag 2
#define SKFChina_ConfigurationAndCommand_ChildNode_order_tag 1
#define SKFChina_ConfigurationAndCommand_ChildNode_totalChildren_tag 2
#define SKFChina_ConfigurationAndCommand_ChildNode_type_tag 3
#define SKFChina_ConfigurationAndCommand_ChildNode_manufacturer_tag 4
#define SKFChina_ConfigurationAndCommand_ChildNode_name_tag 5
#define SKFChina_ConfigurationAndCommand_ChildNode_nameId_tag 6
#define SKFChina_ConfigurationAndCommand_ChildNode_BLESensorName_tag 7
#define SKFChina_ConfigurationAndCommand_ChildNode_macAddr_tag 8
#define SKFChina_ConfigurationAndCommand_ChildNode_description_tag 9
#define SKFChina_ConfigurationAndCommand_ChildrenList_child_tag 1
#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_description_tag 1
#define SKFChina_ConfigurationAndCommand_ConfigPair_specific_config_item_tag 1
#define SKFChina_ConfigurationAndCommand_ConfigPair_fscheduler_config_item_tag 6
#define SKFChina_ConfigurationAndCommand_ConfigPair_general_config_content_tag 2
#define SKFChina_ConfigurationAndCommand_ConfigPair_time_config_content_tag 3
#define SKFChina_ConfigurationAndCommand_ConfigPair_measurement_description_tag 4
#define SKFChina_ConfigurationAndCommand_ConfigPair_bool_config_content_tag 5
#define SKFChina_ConfigurationAndCommand_ConfigPair_general_config_content_uint32_tag 7
#define SKFChina_ConfigurationAndCommand_ConfigPair_general_config_content_int32_tag 8
#define SKFChina_ConfigurationAndCommand_ConfigPair_general_config_content_float_tag 9
#define SKFChina_ConfigurationAndCommand_ConfigPair_work_mode_content_tag 11
#define SKFChina_ConfigurationAndCommand_ConfigPair_gateway_info_content_tag 12
#define SKFChina_ConfigurationAndCommand_ConfigPair_general_config_content_bool_tag 13
#define SKFChina_ConfigurationAndCommand_ConfigPair_mqtt_sec_type_tag 14
#define SKFChina_ConfigurationAndCommand_ConfigPair_ip_addr_tag 15
#define SKFChina_ConfigurationAndCommand_ConfigPair_children_list_tag 16
#define SKFChina_ConfigurationAndCommand_ConfigPair_memory_id_tag 10
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_header_tag 1
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_appVer_tag 2
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_sensor_id_tag 3
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_product_tag 4
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_config_pair_tag 5
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_is_big_endian_tag 6
#define SKFChina_ConfigurationAndCommand_CommandPair_command_tag 1
#define SKFChina_ConfigurationAndCommand_CommandPair_general_config_content_tag 2
#define SKFChina_ConfigurationAndCommand_CommandPair_time_config_content_tag 3
#define SKFChina_ConfigurationAndCommand_CommandPair_bool_config_content_tag 4
#define SKFChina_ConfigurationAndCommand_CommandPair_general_config_content_uint32_tag 5
#define SKFChina_ConfigurationAndCommand_CommandPair_general_config_content_int32_tag 6
#define SKFChina_ConfigurationAndCommand_CommandPair_general_config_content_float_tag 7
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_header_tag 1
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_appVer_tag 2
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_sensor_id_tag 3
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_product_tag 4
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_command_pair_tag 5
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_is_big_endian_tag 6

/* Struct field encoding specification for nanopb */
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    specific_config_item,   1)
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_CALLBACK NULL
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    fscheduler_config_item,   1)
#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_CALLBACK NULL
#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    payload,           4) \
X(a, CALLBACK, REPEATED, MESSAGE,  specific_config_item,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     6) \
X(a, CALLBACK, REPEATED, MESSAGE,  fscheduler_config_item,   7) \
X(a, STATIC,   OPTIONAL, INT32,    memory_id,         8) \
X(a, CALLBACK, OPTIONAL, BYTES,    httpPostUrl,       9) \
X(a, STATIC,   OPTIONAL, UINT32,   name_id,          10)
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_specific_config_item_MSGTYPE SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_fscheduler_config_item_MSGTYPE SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg

#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    product,           4) \
X(a, STATIC,   SINGULAR, UINT32,   config_hash_value,   5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     6) \
X(a, STATIC,   OPTIONAL, MESSAGE,  last_edit_time,    7) \
X(a, CALLBACK, OPTIONAL, BYTES,    config_hash_bitmap,   8) \
X(a, STATIC,   OPTIONAL, UINT32,   config_hash_len_byte,   9)
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_last_edit_time_MSGTYPE SKFChina_ConfigurationAndCommand_TimeArrayElement

#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    product,           4) \
X(a, CALLBACK, REPEATED, MESSAGE,  config_pair,       5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     6)
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_config_pair_MSGTYPE SKFChina_ConfigurationAndCommand_ConfigPair

#define SKFChina_ConfigurationAndCommand_TimeArrayElement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   time,              1)
#define SKFChina_ConfigurationAndCommand_TimeArrayElement_CALLBACK NULL
#define SKFChina_ConfigurationAndCommand_TimeArrayElement_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_TimeArray_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  time,              1)
#define SKFChina_ConfigurationAndCommand_TimeArray_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_TimeArray_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_TimeArray_time_MSGTYPE SKFChina_ConfigurationAndCommand_TimeArrayElement

#define SKFChina_ConfigurationAndCommand_BoolArrayElement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     YesOrNo,           1)
#define SKFChina_ConfigurationAndCommand_BoolArrayElement_CALLBACK NULL
#define SKFChina_ConfigurationAndCommand_BoolArrayElement_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_BoolArray_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  YesOrNo,           1)
#define SKFChina_ConfigurationAndCommand_BoolArray_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_BoolArray_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_BoolArray_YesOrNo_MSGTYPE SKFChina_ConfigurationAndCommand_BoolArrayElement

#define SKFChina_ConfigurationAndCommand_WorkModePair_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    work_mode,         1) \
X(a, CALLBACK, SINGULAR, BYTES,    parameter,         2)
#define SKFChina_ConfigurationAndCommand_WorkModePair_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_WorkModePair_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    mac_address,       1) \
X(a, STATIC,   SINGULAR, UINT32,   name_id,           2)
#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    specific_config_item,   2) \
X(a, CALLBACK, ONEOF,    BYTES,    (config_content,general_config_content,config_content.general_config_content),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,time_config_content,config_content.time_config_content),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,bool_config_content,config_content.bool_config_content),   6) \
X(a, STATIC,   ONEOF,    UINT32,   (config_content,general_config_content_uint32,config_content.general_config_content_uint32),   7) \
X(a, STATIC,   ONEOF,    INT32,    (config_content,general_config_content_int32,config_content.general_config_content_int32),   8) \
X(a, STATIC,   ONEOF,    FLOAT,    (config_content,general_config_content_float,config_content.general_config_content_float),   9) \
X(a, STATIC,   OPTIONAL, INT32,    memory_id,        10) \
X(a, STATIC,   ONEOF,    BOOL,     (config_content,general_config_content_bool,config_content.general_config_content_bool),  11)
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_config_content_time_config_content_MSGTYPE SKFChina_ConfigurationAndCommand_TimeArray
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_config_content_bool_config_content_MSGTYPE SKFChina_ConfigurationAndCommand_BoolArray

#define SKFChina_ConfigurationAndCommand_DescConfigPair_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   time,              1) \
X(a, CALLBACK, REPEATED, MESSAGE,  metric,            2)
#define SKFChina_ConfigurationAndCommand_DescConfigPair_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_DescConfigPair_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_DescConfigPair_metric_MSGTYPE SKFChina_ConfigurationAndCommand_DescConfigPairMetric

#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    secType,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    parameter,         2)
#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_IpAddr_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     isIpv4,            1) \
X(a, CALLBACK, SINGULAR, BYTES,    addr,              2)
#define SKFChina_ConfigurationAndCommand_IpAddr_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_IpAddr_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_ChildNode_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   order,             1) \
X(a, STATIC,   SINGULAR, UINT32,   totalChildren,     2) \
X(a, CALLBACK, OPTIONAL, BYTES,    type,              3) \
X(a, CALLBACK, OPTIONAL, BYTES,    manufacturer,      4) \
X(a, CALLBACK, OPTIONAL, BYTES,    name,              5) \
X(a, STATIC,   SINGULAR, UINT32,   nameId,            6) \
X(a, CALLBACK, OPTIONAL, BYTES,    BLESensorName,     7) \
X(a, CALLBACK, SINGULAR, BYTES,    macAddr,           8) \
X(a, CALLBACK, SINGULAR, BYTES,    description,       9)
#define SKFChina_ConfigurationAndCommand_ChildNode_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_ChildNode_DEFAULT NULL

#define SKFChina_ConfigurationAndCommand_ChildrenList_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  child,             1)
#define SKFChina_ConfigurationAndCommand_ChildrenList_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_ChildrenList_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_ChildrenList_child_MSGTYPE SKFChina_ConfigurationAndCommand_ChildNode

#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, MESSAGE,  description,       1)
#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_description_MSGTYPE SKFChina_ConfigurationAndCommand_DescConfigPair

#define SKFChina_ConfigurationAndCommand_ConfigPair_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    UENUM,    (config_item,specific_config_item,config_item.specific_config_item),   1) \
X(a, CALLBACK, ONEOF,    BYTES,    (config_content,general_config_content,config_content.general_config_content),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,time_config_content,config_content.time_config_content),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,measurement_description,config_content.measurement_description),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,bool_config_content,config_content.bool_config_content),   5) \
X(a, STATIC,   ONEOF,    UENUM,    (config_item,fscheduler_config_item,config_item.fscheduler_config_item),   6) \
X(a, STATIC,   ONEOF,    UINT32,   (config_content,general_config_content_uint32,config_content.general_config_content_uint32),   7) \
X(a, STATIC,   ONEOF,    INT32,    (config_content,general_config_content_int32,config_content.general_config_content_int32),   8) \
X(a, STATIC,   ONEOF,    FLOAT,    (config_content,general_config_content_float,config_content.general_config_content_float),   9) \
X(a, STATIC,   OPTIONAL, INT32,    memory_id,        10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,work_mode_content,config_content.work_mode_content),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,gateway_info_content,config_content.gateway_info_content),  12) \
X(a, STATIC,   ONEOF,    BOOL,     (config_content,general_config_content_bool,config_content.general_config_content_bool),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,mqtt_sec_type,config_content.mqtt_sec_type),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,ip_addr,config_content.ip_addr),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (config_content,children_list,config_content.children_list),  16)
#define SKFChina_ConfigurationAndCommand_ConfigPair_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_ConfigPair_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_time_config_content_MSGTYPE SKFChina_ConfigurationAndCommand_TimeArray
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_measurement_description_MSGTYPE SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_bool_config_content_MSGTYPE SKFChina_ConfigurationAndCommand_BoolArray
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_work_mode_content_MSGTYPE SKFChina_ConfigurationAndCommand_WorkModePair
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_gateway_info_content_MSGTYPE SKFChina_ConfigurationAndCommand_GatewayInfoPair
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_mqtt_sec_type_MSGTYPE SKFChina_ConfigurationAndCommand_MqttSecTypePair
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_ip_addr_MSGTYPE SKFChina_ConfigurationAndCommand_IpAddr
#define SKFChina_ConfigurationAndCommand_ConfigPair_config_content_children_list_MSGTYPE SKFChina_ConfigurationAndCommand_ChildrenList

#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    product,           4) \
X(a, CALLBACK, REPEATED, MESSAGE,  config_pair,       5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     6)
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_config_pair_MSGTYPE SKFChina_ConfigurationAndCommand_ConfigPair

#define SKFChina_ConfigurationAndCommand_CommandPair_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    command,           1) \
X(a, CALLBACK, ONEOF,    BYTES,    (command_para,general_config_content,command_para.general_config_content),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_para,time_config_content,command_para.time_config_content),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command_para,bool_config_content,command_para.bool_config_content),   4) \
X(a, STATIC,   ONEOF,    UINT32,   (command_para,general_config_content_uint32,command_para.general_config_content_uint32),   5) \
X(a, STATIC,   ONEOF,    INT32,    (command_para,general_config_content_int32,command_para.general_config_content_int32),   6) \
X(a, STATIC,   ONEOF,    FLOAT,    (command_para,general_config_content_float,command_para.general_config_content_float),   7)
#define SKFChina_ConfigurationAndCommand_CommandPair_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_CommandPair_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_CommandPair_command_para_time_config_content_MSGTYPE SKFChina_ConfigurationAndCommand_TimeArray
#define SKFChina_ConfigurationAndCommand_CommandPair_command_para_bool_config_content_MSGTYPE SKFChina_ConfigurationAndCommand_BoolArray

#define SKFChina_ConfigurationAndCommand_CommandDisseminate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    product,           4) \
X(a, STATIC,   OPTIONAL, MESSAGE,  command_pair,      5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     6)
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_CALLBACK pb_default_field_callback
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_DEFAULT NULL
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_command_pair_MSGTYPE SKFChina_ConfigurationAndCommand_CommandPair

extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_ConfigRetrieve_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_ConfigHashUpload_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_SpecificConfigUpload_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_TimeArrayElement_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_TimeArray_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_BoolArrayElement_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_BoolArray_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_WorkModePair_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_GatewayInfoPair_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_DescConfigPairMetric_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_DescConfigPair_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_MqttSecTypePair_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_IpAddr_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_ChildNode_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_ChildrenList_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_ConfigPair_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_ConfigDisseminate_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_CommandPair_msg;
extern const pb_msgdesc_t SKFChina_ConfigurationAndCommand_CommandDisseminate_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_fields &SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_msg
#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_fields &SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_msg
#define SKFChina_ConfigurationAndCommand_ConfigRetrieve_fields &SKFChina_ConfigurationAndCommand_ConfigRetrieve_msg
#define SKFChina_ConfigurationAndCommand_ConfigHashUpload_fields &SKFChina_ConfigurationAndCommand_ConfigHashUpload_msg
#define SKFChina_ConfigurationAndCommand_SpecificConfigUpload_fields &SKFChina_ConfigurationAndCommand_SpecificConfigUpload_msg
#define SKFChina_ConfigurationAndCommand_TimeArrayElement_fields &SKFChina_ConfigurationAndCommand_TimeArrayElement_msg
#define SKFChina_ConfigurationAndCommand_TimeArray_fields &SKFChina_ConfigurationAndCommand_TimeArray_msg
#define SKFChina_ConfigurationAndCommand_BoolArrayElement_fields &SKFChina_ConfigurationAndCommand_BoolArrayElement_msg
#define SKFChina_ConfigurationAndCommand_BoolArray_fields &SKFChina_ConfigurationAndCommand_BoolArray_msg
#define SKFChina_ConfigurationAndCommand_WorkModePair_fields &SKFChina_ConfigurationAndCommand_WorkModePair_msg
#define SKFChina_ConfigurationAndCommand_GatewayInfoPair_fields &SKFChina_ConfigurationAndCommand_GatewayInfoPair_msg
#define SKFChina_ConfigurationAndCommand_DescConfigPairMetric_fields &SKFChina_ConfigurationAndCommand_DescConfigPairMetric_msg
#define SKFChina_ConfigurationAndCommand_DescConfigPair_fields &SKFChina_ConfigurationAndCommand_DescConfigPair_msg
#define SKFChina_ConfigurationAndCommand_MqttSecTypePair_fields &SKFChina_ConfigurationAndCommand_MqttSecTypePair_msg
#define SKFChina_ConfigurationAndCommand_IpAddr_fields &SKFChina_ConfigurationAndCommand_IpAddr_msg
#define SKFChina_ConfigurationAndCommand_ChildNode_fields &SKFChina_ConfigurationAndCommand_ChildNode_msg
#define SKFChina_ConfigurationAndCommand_ChildrenList_fields &SKFChina_ConfigurationAndCommand_ChildrenList_msg
#define SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_fields &SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_msg
#define SKFChina_ConfigurationAndCommand_ConfigPair_fields &SKFChina_ConfigurationAndCommand_ConfigPair_msg
#define SKFChina_ConfigurationAndCommand_ConfigDisseminate_fields &SKFChina_ConfigurationAndCommand_ConfigDisseminate_msg
#define SKFChina_ConfigurationAndCommand_CommandPair_fields &SKFChina_ConfigurationAndCommand_CommandPair_msg
#define SKFChina_ConfigurationAndCommand_CommandDisseminate_fields &SKFChina_ConfigurationAndCommand_CommandDisseminate_msg

/* Maximum encoded size of messages (where known) */
/* SKFChina_ConfigurationAndCommand_ConfigRetrieve_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_ConfigHashUpload_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_SpecificConfigUpload_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_TimeArray_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_BoolArray_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_WorkModePair_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_GatewayInfoPair_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_DescConfigPairMetric_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_DescConfigPair_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_MqttSecTypePair_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_IpAddr_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_ChildNode_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_ChildrenList_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_WakeUpToSenseDesc_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_ConfigPair_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_ConfigDisseminate_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_CommandPair_size depends on runtime parameters */
/* SKFChina_ConfigurationAndCommand_CommandDisseminate_size depends on runtime parameters */
#define SKFChina_ConfigurationAndCommand_BoolArrayElement_size 2
#define SKFChina_ConfigurationAndCommand_SpecificConfigItemMsg_size 3
#define SKFChina_ConfigurationAndCommand_TimeArrayElement_size 11
#define SKFChina_ConfigurationAndCommand_fSchedulerConfigItemMsg_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
