/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "Debug.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SKFChina_Debug_DebugMsgUniversal, SKFChina_Debug_DebugMsgUniversal, AUTO)


PB_BIND(SKFChina_Debug_DebugMetric, SKFChina_Debug_DebugMetric, AUTO)


PB_BIND(SKFChina_Debug_DebugMessage, SKFChina_Debug_DebugMessage, AUTO)



