/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SKFCHINA_DEBUG_DEBUG_PB_H_INCLUDED
#define PB_SKFCHINA_DEBUG_DEBUG_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"
#include "Froto.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SKFChina_Debug_DebugMsgUniversal { /* In the current design: field number 2 have been used. */
    /* Unix timestamp, 0 time zone, unit is ms */
    bool has_time;
    uint64_t time;
    pb_callback_t message_content;
} SKFChina_Debug_DebugMsgUniversal;

typedef struct _SKFChina_Debug_DebugMetric { /* In the current design: field number 3 have been used. */
    /* Unix timestamp, 0 time zone, unit is ms */
    bool has_time;
    uint64_t time;
    uint32_t MetricId;
    pb_callback_t message_content;
} SKFChina_Debug_DebugMetric;

typedef struct _SKFChina_Debug_DebugMessage { /* In the current design: field numbers 1 - 7 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The type of product */
    SKFChina_Common_ProductType product;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
    pb_callback_t debug_message;
    pb_callback_t debug_metric;
} SKFChina_Debug_DebugMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SKFChina_Debug_DebugMsgUniversal_init_default {false, 0, {{NULL}, NULL}}
#define SKFChina_Debug_DebugMetric_init_default  {false, 0, 0, {{NULL}, NULL}}
#define SKFChina_Debug_DebugMessage_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}
#define SKFChina_Debug_DebugMsgUniversal_init_zero {false, 0, {{NULL}, NULL}}
#define SKFChina_Debug_DebugMetric_init_zero     {false, 0, 0, {{NULL}, NULL}}
#define SKFChina_Debug_DebugMessage_init_zero    {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, false, 0, {{NULL}, NULL}, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SKFChina_Debug_DebugMsgUniversal_time_tag 1
#define SKFChina_Debug_DebugMsgUniversal_message_content_tag 2
#define SKFChina_Debug_DebugMetric_time_tag      1
#define SKFChina_Debug_DebugMetric_MetricId_tag  2
#define SKFChina_Debug_DebugMetric_message_content_tag 3
#define SKFChina_Debug_DebugMessage_header_tag   1
#define SKFChina_Debug_DebugMessage_appVer_tag   2
#define SKFChina_Debug_DebugMessage_sensor_id_tag 3
#define SKFChina_Debug_DebugMessage_product_tag  4
#define SKFChina_Debug_DebugMessage_is_big_endian_tag 5
#define SKFChina_Debug_DebugMessage_debug_message_tag 6
#define SKFChina_Debug_DebugMessage_debug_metric_tag 7

/* Struct field encoding specification for nanopb */
#define SKFChina_Debug_DebugMsgUniversal_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   time,              1) \
X(a, CALLBACK, SINGULAR, BYTES,    message_content,   2)
#define SKFChina_Debug_DebugMsgUniversal_CALLBACK pb_default_field_callback
#define SKFChina_Debug_DebugMsgUniversal_DEFAULT NULL

#define SKFChina_Debug_DebugMetric_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, UINT64,   time,              1) \
X(a, STATIC,   SINGULAR, UINT32,   MetricId,          2) \
X(a, CALLBACK, SINGULAR, BYTES,    message_content,   3)
#define SKFChina_Debug_DebugMetric_CALLBACK pb_default_field_callback
#define SKFChina_Debug_DebugMetric_DEFAULT NULL

#define SKFChina_Debug_DebugMessage_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    product,           4) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     5) \
X(a, CALLBACK, REPEATED, MESSAGE,  debug_message,     6) \
X(a, CALLBACK, REPEATED, MESSAGE,  debug_metric,      7)
#define SKFChina_Debug_DebugMessage_CALLBACK pb_default_field_callback
#define SKFChina_Debug_DebugMessage_DEFAULT NULL
#define SKFChina_Debug_DebugMessage_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_Debug_DebugMessage_debug_message_MSGTYPE SKFChina_Debug_DebugMsgUniversal
#define SKFChina_Debug_DebugMessage_debug_metric_MSGTYPE SKFChina_Debug_DebugMetric

extern const pb_msgdesc_t SKFChina_Debug_DebugMsgUniversal_msg;
extern const pb_msgdesc_t SKFChina_Debug_DebugMetric_msg;
extern const pb_msgdesc_t SKFChina_Debug_DebugMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKFChina_Debug_DebugMsgUniversal_fields &SKFChina_Debug_DebugMsgUniversal_msg
#define SKFChina_Debug_DebugMetric_fields &SKFChina_Debug_DebugMetric_msg
#define SKFChina_Debug_DebugMessage_fields &SKFChina_Debug_DebugMessage_msg

/* Maximum encoded size of messages (where known) */
/* SKFChina_Debug_DebugMsgUniversal_size depends on runtime parameters */
/* SKFChina_Debug_DebugMetric_size depends on runtime parameters */
/* SKFChina_Debug_DebugMessage_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
