/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SKFCHINA_APP_DEVICEAPPBULLETGATEWAY_PB_H_INCLUDED
#define PB_SKFCHINA_APP_DEVICEAPPBULLETGATEWAY_PB_H_INCLUDED
#include <pb.h>
#include "Froto.pb.h"
#include "SensingDataUpload.pb.h"
#include "FirmwareUpdateOverTheAir.pb.h"
#include "ConfigurationAndCommand.pb.h"
#include "Debug.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _SKFChina_App_AppMessage { /* In the current design: field numbers 1 - 21 have been used. */
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    pb_size_t which__messages;
    union {
        /* Basic (sensing) data related */
        SKFChina_SensingDataUpload_DataUpload data_upload;
        SKFChina_SensingDataUpload_DataSelectionDisseminate data_selection;
        /* Configuration and command related */
        SKFChina_ConfigurationAndCommand_ConfigRetrieve config_retrieve;
        SKFChina_ConfigurationAndCommand_ConfigHashUpload config_hash_upload;
        SKFChina_ConfigurationAndCommand_SpecificConfigUpload specific_config_upload;
        SKFChina_ConfigurationAndCommand_ConfigDisseminate config_dissem;
        SKFChina_ConfigurationAndCommand_CommandDisseminate command_dissem;
        /* FUOTA related */
        SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve version_retrieve;
        SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload current_version_upload;
        SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload last_fuota_upload;
        SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate fuota_notify_dissem;
        SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload fuota_status;
        SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate image_block_dissem;
        SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest image_block_request;
        /* Ack message (Froto layer) */
        SKFChina_Froto_FrotoAckMsg ack;
        /* Debug related */
        SKFChina_Debug_DebugMessage debug_message;
        SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate file_notify_dissem;
        /* File upload */
        SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate file_notify_upload;
        SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate image_block_upload;
        SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest image_block_retrieve;
    } _messages;
} SKFChina_App_AppMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SKFChina_App_AppMessage_init_default     {0, 0, {SKFChina_SensingDataUpload_DataUpload_init_default}}
#define SKFChina_App_AppMessage_init_zero        {0, 0, {SKFChina_SensingDataUpload_DataUpload_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define SKFChina_App_AppMessage_appVer_tag       1
#define SKFChina_App_AppMessage_data_upload_tag  2
#define SKFChina_App_AppMessage_data_selection_tag 3
#define SKFChina_App_AppMessage_config_retrieve_tag 4
#define SKFChina_App_AppMessage_config_hash_upload_tag 5
#define SKFChina_App_AppMessage_specific_config_upload_tag 6
#define SKFChina_App_AppMessage_config_dissem_tag 7
#define SKFChina_App_AppMessage_command_dissem_tag 8
#define SKFChina_App_AppMessage_version_retrieve_tag 9
#define SKFChina_App_AppMessage_current_version_upload_tag 10
#define SKFChina_App_AppMessage_last_fuota_upload_tag 11
#define SKFChina_App_AppMessage_fuota_notify_dissem_tag 12
#define SKFChina_App_AppMessage_fuota_status_tag 13
#define SKFChina_App_AppMessage_image_block_dissem_tag 14
#define SKFChina_App_AppMessage_image_block_request_tag 15
#define SKFChina_App_AppMessage_ack_tag          16
#define SKFChina_App_AppMessage_debug_message_tag 17
#define SKFChina_App_AppMessage_file_notify_dissem_tag 18
#define SKFChina_App_AppMessage_file_notify_upload_tag 19
#define SKFChina_App_AppMessage_image_block_upload_tag 20
#define SKFChina_App_AppMessage_image_block_retrieve_tag 21

/* Struct field encoding specification for nanopb */
#define SKFChina_App_AppMessage_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,data_upload,_messages.data_upload),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,data_selection,_messages.data_selection),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,config_retrieve,_messages.config_retrieve),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,config_hash_upload,_messages.config_hash_upload),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,specific_config_upload,_messages.specific_config_upload),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,config_dissem,_messages.config_dissem),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,command_dissem,_messages.command_dissem),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,version_retrieve,_messages.version_retrieve),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,current_version_upload,_messages.current_version_upload),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,last_fuota_upload,_messages.last_fuota_upload),  11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,fuota_notify_dissem,_messages.fuota_notify_dissem),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,fuota_status,_messages.fuota_status),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,image_block_dissem,_messages.image_block_dissem),  14) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,image_block_request,_messages.image_block_request),  15) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,ack,_messages.ack),  16) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,debug_message,_messages.debug_message),  17) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,file_notify_dissem,_messages.file_notify_dissem),  18) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,file_notify_upload,_messages.file_notify_upload),  19) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,image_block_upload,_messages.image_block_upload),  20) \
X(a, STATIC,   ONEOF,    MESSAGE,  (_messages,image_block_retrieve,_messages.image_block_retrieve),  21)
#define SKFChina_App_AppMessage_CALLBACK NULL
#define SKFChina_App_AppMessage_DEFAULT NULL
#define SKFChina_App_AppMessage__messages_data_upload_MSGTYPE SKFChina_SensingDataUpload_DataUpload
#define SKFChina_App_AppMessage__messages_data_selection_MSGTYPE SKFChina_SensingDataUpload_DataSelectionDisseminate
#define SKFChina_App_AppMessage__messages_config_retrieve_MSGTYPE SKFChina_ConfigurationAndCommand_ConfigRetrieve
#define SKFChina_App_AppMessage__messages_config_hash_upload_MSGTYPE SKFChina_ConfigurationAndCommand_ConfigHashUpload
#define SKFChina_App_AppMessage__messages_specific_config_upload_MSGTYPE SKFChina_ConfigurationAndCommand_SpecificConfigUpload
#define SKFChina_App_AppMessage__messages_config_dissem_MSGTYPE SKFChina_ConfigurationAndCommand_ConfigDisseminate
#define SKFChina_App_AppMessage__messages_command_dissem_MSGTYPE SKFChina_ConfigurationAndCommand_CommandDisseminate
#define SKFChina_App_AppMessage__messages_version_retrieve_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve
#define SKFChina_App_AppMessage__messages_current_version_upload_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload
#define SKFChina_App_AppMessage__messages_last_fuota_upload_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload
#define SKFChina_App_AppMessage__messages_fuota_notify_dissem_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate
#define SKFChina_App_AppMessage__messages_fuota_status_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload
#define SKFChina_App_AppMessage__messages_image_block_dissem_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate
#define SKFChina_App_AppMessage__messages_image_block_request_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest
#define SKFChina_App_AppMessage__messages_ack_MSGTYPE SKFChina_Froto_FrotoAckMsg
#define SKFChina_App_AppMessage__messages_debug_message_MSGTYPE SKFChina_Debug_DebugMessage
#define SKFChina_App_AppMessage__messages_file_notify_dissem_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate
#define SKFChina_App_AppMessage__messages_file_notify_upload_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate
#define SKFChina_App_AppMessage__messages_image_block_upload_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate
#define SKFChina_App_AppMessage__messages_image_block_retrieve_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest

extern const pb_msgdesc_t SKFChina_App_AppMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKFChina_App_AppMessage_fields &SKFChina_App_AppMessage_msg

/* Maximum encoded size of messages (where known) */
#if defined(SKFChina_SensingDataUpload_DataUpload_size) && defined(SKFChina_SensingDataUpload_DataSelectionDisseminate_size) && defined(SKFChina_ConfigurationAndCommand_ConfigRetrieve_size) && defined(SKFChina_ConfigurationAndCommand_ConfigHashUpload_size) && defined(SKFChina_ConfigurationAndCommand_SpecificConfigUpload_size) && defined(SKFChina_ConfigurationAndCommand_ConfigDisseminate_size) && defined(SKFChina_ConfigurationAndCommand_CommandDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_size) && defined(SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_size) && defined(SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_size) && defined(SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size) && defined(SKFChina_Froto_FrotoAckMsg_size) && defined(SKFChina_Debug_DebugMessage_size) && defined(SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size)
union SKFChina_App_AppMessage__messages_size_union {char f2[(6 + SKFChina_SensingDataUpload_DataUpload_size)]; char f3[(6 + SKFChina_SensingDataUpload_DataSelectionDisseminate_size)]; char f4[(6 + SKFChina_ConfigurationAndCommand_ConfigRetrieve_size)]; char f5[(6 + SKFChina_ConfigurationAndCommand_ConfigHashUpload_size)]; char f6[(6 + SKFChina_ConfigurationAndCommand_SpecificConfigUpload_size)]; char f7[(6 + SKFChina_ConfigurationAndCommand_ConfigDisseminate_size)]; char f8[(6 + SKFChina_ConfigurationAndCommand_CommandDisseminate_size)]; char f9[(6 + SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_size)]; char f10[(6 + SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_size)]; char f11[(6 + SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_size)]; char f12[(6 + SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_size)]; char f13[(6 + SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_size)]; char f14[(6 + SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_size)]; char f15[(6 + SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size)]; char f16[(7 + SKFChina_Froto_FrotoAckMsg_size)]; char f17[(7 + SKFChina_Debug_DebugMessage_size)]; char f18[(7 + SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_size)]; char f19[(7 + SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_size)]; char f20[(7 + SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_size)]; char f21[(7 + SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size)];};
#endif
#if defined(SKFChina_SensingDataUpload_DataUpload_size) && defined(SKFChina_SensingDataUpload_DataSelectionDisseminate_size) && defined(SKFChina_ConfigurationAndCommand_ConfigRetrieve_size) && defined(SKFChina_ConfigurationAndCommand_ConfigHashUpload_size) && defined(SKFChina_ConfigurationAndCommand_SpecificConfigUpload_size) && defined(SKFChina_ConfigurationAndCommand_ConfigDisseminate_size) && defined(SKFChina_ConfigurationAndCommand_CommandDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_size) && defined(SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_size) && defined(SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_size) && defined(SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size) && defined(SKFChina_Froto_FrotoAckMsg_size) && defined(SKFChina_Debug_DebugMessage_size) && defined(SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_size) && defined(SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size)
#define SKFChina_App_AppMessage_size             (6 + sizeof(union SKFChina_App_AppMessage__messages_size_union))
#endif

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
