/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SKFCHINA_FIRMWAREUPDATEOVERTHEAIR_FIRMWAREUPDATEOVERTHEAIR_PB_H_INCLUDED
#define PB_SKFCHINA_FIRMWAREUPDATEOVERTHEAIR_FIRMWAREUPDATEOVERTHEAIR_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"
#include "Froto.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* What to retrieve */
typedef enum _SKFChina_FirmwareUpdateOverTheAir_RetrievePayload {
    /* 0 - 2 used */
    SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_UNKNOWN_RETRIEVE = 0,
    SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_CURRENT_VERSION = 1,
    SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_LAST_FUOTA = 2
} SKFChina_FirmwareUpdateOverTheAir_RetrievePayload;

/* The firmware update status */
typedef enum _SKFChina_FirmwareUpdateOverTheAir_UpdateStatus {
    /* 0 - 9 used */
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_UNKNOWN_STATUS = 0,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_NOTIFICATION_RECEIVED = 1,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_IMAGE_RECEIVING = 2,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_IMAGE_RECEIVED = 3,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_IMAGE_CHECKING = 4,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_IMAGE_VALID = 6,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_IMAGE_INVALID = 7,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_SUCCESSFUL = 8,
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_FAIL = 9
} SKFChina_FirmwareUpdateOverTheAir_UpdateStatus;

/* Struct definitions */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo { /* In the current design: field numbers 1 - 5 have been used. */
    /* FUOTA task ID */
    uint32_t fuota_task_id;
    /* When updated (unix timestamp, 0 time zone, unit is ms) */
    uint64_t update_time;
    /* The update communication method */
    SKFChina_Common_CommunicationType update_method;
    /* The update type: diff or whole */
    SKFChina_Common_FUOTAType update_type;
    /* The image size */
    uint32_t update_image_size_bytes;
} SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo;

/* To retrieve the version information */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve { /* In the current design: field numbers 1 - 5 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    SKFChina_FirmwareUpdateOverTheAir_RetrievePayload payload;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve;

/* The retrieve reply for @p CURRENT_VERSION or upload directly the current version information */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload { /* In the current design: field numbers 1 - 9 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The hardware type */
    SKFChina_Common_HardwareType hardware_type;
    /* The hardware version
 (TODO: specify how to convert the hardware version to a uint32 value) */
    uint32_t hardware_version;
    /* The firmware version = (Major << 16) + (Minor << 8) + (Bugfix) */
    uint32_t firmware_version;
    /* The gnu build id */
    bool has_build_id;
    uint32_t build_id;
    /* Some update information of the current version */
    bool has_current_version_supplementary_update_info;
    SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo current_version_supplementary_update_info;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload;

/* The retrieve reply for @p LAST_FUOTA */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload { /* In the current design: field numbers 1 - 9 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The hardware type */
    SKFChina_Common_HardwareType hardware_type;
    /* The hardware version
 (TODO: specify how to convert the hardware version to a uint32 value) */
    uint32_t hardware_version;
    /* The firmware version = (Major << 16) + (Minor << 8) + (Bugfix) */
    uint32_t firmware_version;
    /* The gnu build id */
    bool has_build_id;
    uint32_t build_id;
    /* Some update information of the last update */
    bool has_last_update_supplementary_info;
    SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo last_update_supplementary_info;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload;

/* To report the current FUOTA status */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload { /* In the current design: field numbers 1 - 8 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The update status */
    SKFChina_FirmwareUpdateOverTheAir_UpdateStatus update_status;
    /* FUOTA task ID */
    uint32_t fuota_task_id;
    /* Received bytes */
    uint32_t received_bytes;
    /* Some debug messages can be uploaded */
    pb_callback_t debug_messages;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload;

typedef struct _SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp {
    /* In the current design: field number 1 has been used. */
    pb_callback_t url;
} SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp;

typedef struct _SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt {
    /* In the current design: field numbers 1 - 2 have been used. */
    pb_callback_t url;
    pb_callback_t mqtt_topic;
} SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt;

typedef struct _SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts {
    /* TODO: to be designed (if using BLE OTS) */
    pb_callback_t TODO;
    /* In the current design: field number 2 has been used.
 True is BLE UART, otherwise BLE OTS */
    bool isBLEUart;
} SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts;

/* The FUOTA notification to the sensor */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate { /* In the current design: field numbers 1 - 20 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* FUOTA task ID */
    uint32_t fuota_task_id;
    SKFChina_Common_HardwareType target_hardware_type;
    /* The to-be-updated target hardware version
 (TODO: specify how to convert the hardware version to a uint32 value) */
    uint32_t target_hardware_version;
    /* The to-be-updated firmware version
 The firmware version = (Major << 16) + (Minor << 8) + (Bugfix) */
    uint32_t firmware_version;
    /* The gnu build id of the to-be-updated firmware */
    bool has_build_id;
    uint32_t build_id;
    /* Force to perform the FUOTA no matter the version is later than the current one
 [default = false] */
    bool force_fuota;
    /* The update communication method */
    SKFChina_Common_CommunicationType update_method;
    /* The update type: diff or whole */
    SKFChina_Common_FUOTAType update_type;
    pb_size_t which_fuota_method;
    union {
        SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp fuota_with_http;
        SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt fuota_with_froto_over_mqtt;
        SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts fuota_with_froto_over_ble_ots; /* BLE OTS or BLE uart */
    } fuota_method;
    pb_size_t which_check_value;
    union {
        pb_callback_t md5_value; /* 32-bit md5 */
        pb_callback_t sha1_value;
        uint32_t elf_hash_value;
    } check_value;
    /* The supplementary information (just in case) */
    pb_callback_t supplementary_info;
    /* Encryption: indicate which encryption is adopted for @p ImageBlockDisseminate.image_content. */
    bool has_encryp;
    SKFChina_Common_Encryption encryp;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate;

/* The normal file notification to the sensor */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate { /* In the current design: field numbers 1 - 15 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    SKFChina_Common_FileType file_type;
    /* Task ID */
    uint32_t task_id;
    /* The update communication method */
    SKFChina_Common_CommunicationType update_method;
    pb_size_t which_fuota_method;
    union {
        SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp fuota_with_http;
        SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt fuota_with_froto_over_mqtt;
        SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts fuota_with_froto_over_ble_ots; /* BLE OTS or BLE uart */
    } fuota_method;
    /* The supplementary information (just in case) */
    pb_callback_t supplementary_info;
    pb_size_t which_check_value;
    union {
        pb_callback_t md5_value; /* 32-bit md5 */
        pb_callback_t sha1_value;
        uint32_t elf_hash_value;
    } check_value;
    /* Encryption: indicate which encryption is adopted for @p ImageBlockDisseminate.image_content. */
    bool has_encryp;
    SKFChina_Common_Encryption encryp;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate;

/* The request reply for @p SPECIFIC_IMAGEBLOCK or disseminate directly image blocks */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate { /* In the current design: field numbers 1 - 9 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    pb_size_t which_task_id;
    union {
        uint32_t fuota_task_id;
        uint32_t file_task_id;
    } task_id;
    /* offset to the start of the image */
    uint32_t offset;
    /* The image content */
    pb_callback_t image_content;
    /* hash value of the data: elf hash adopted. */
    uint32_t hash_value;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate;

/* To request a specific block (used for, e.g., some blocks are missed) */
typedef struct _SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest { /* In the current design: field numbers 1 - 8 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* Offset to the start of the image */
    uint32_t offset;
    /* The size */
    uint32_t size;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
    pb_size_t which_task_id;
    union {
        uint32_t fuota_task_id;
        uint32_t file_task_id;
    } task_id;
} SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_MIN SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_UNKNOWN_RETRIEVE
#define _SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_MAX SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_LAST_FUOTA
#define _SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_ARRAYSIZE ((SKFChina_FirmwareUpdateOverTheAir_RetrievePayload)(SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_LAST_FUOTA+1))

#define _SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_MIN SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_UNKNOWN_STATUS
#define _SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_MAX SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_FAIL
#define _SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_ARRAYSIZE ((SKFChina_FirmwareUpdateOverTheAir_UpdateStatus)(SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_FUOTA_FAIL+1))

#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_update_method_ENUMTYPE SKFChina_Common_CommunicationType
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_update_type_ENUMTYPE SKFChina_Common_FUOTAType

#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_payload_ENUMTYPE SKFChina_FirmwareUpdateOverTheAir_RetrievePayload

#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_hardware_type_ENUMTYPE SKFChina_Common_HardwareType

#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_hardware_type_ENUMTYPE SKFChina_Common_HardwareType

#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_update_status_ENUMTYPE SKFChina_FirmwareUpdateOverTheAir_UpdateStatus




#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_target_hardware_type_ENUMTYPE SKFChina_Common_HardwareType
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_update_method_ENUMTYPE SKFChina_Common_CommunicationType
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_update_type_ENUMTYPE SKFChina_Common_FUOTAType
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_encryp_ENUMTYPE SKFChina_Common_Encryption

#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_file_type_ENUMTYPE SKFChina_Common_FileType
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_update_method_ENUMTYPE SKFChina_Common_CommunicationType
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_encryp_ENUMTYPE SKFChina_Common_Encryption




/* Initializer values for message structs */
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_init_default {0, 0, _SKFChina_Common_CommunicationType_MIN, _SKFChina_Common_FUOTAType_MIN, 0}
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_MIN, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_HardwareType_MIN, 0, 0, false, 0, false, SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_init_default, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_HardwareType_MIN, 0, 0, false, 0, false, SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_init_default, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_MIN, 0, 0, {{NULL}, NULL}, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_init_default {{{NULL}, NULL}}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_init_default {{{NULL}, NULL}, {{NULL}, NULL}}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_init_default {{{NULL}, NULL}, 0}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, 0, _SKFChina_Common_HardwareType_MIN, 0, 0, false, 0, 0, _SKFChina_Common_CommunicationType_MIN, _SKFChina_Common_FUOTAType_MIN, 0, {SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_init_default}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}, false, _SKFChina_Common_Encryption_MIN, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, _SKFChina_Common_FileType_MIN, 0, _SKFChina_Common_CommunicationType_MIN, 0, {SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_init_default}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, false, _SKFChina_Common_Encryption_MIN, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, 0, {0}, 0, {{NULL}, NULL}, 0, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, 0, 0, false, 0, 0, {0}}
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_init_zero {0, 0, _SKFChina_Common_CommunicationType_MIN, _SKFChina_Common_FUOTAType_MIN, 0}
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_FirmwareUpdateOverTheAir_RetrievePayload_MIN, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_HardwareType_MIN, 0, 0, false, 0, false, SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_init_zero, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_HardwareType_MIN, 0, 0, false, 0, false, SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_init_zero, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_FirmwareUpdateOverTheAir_UpdateStatus_MIN, 0, 0, {{NULL}, NULL}, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_init_zero {{{NULL}, NULL}}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_init_zero {{{NULL}, NULL}, {{NULL}, NULL}}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_init_zero {{{NULL}, NULL}, 0}
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, 0, _SKFChina_Common_HardwareType_MIN, 0, 0, false, 0, 0, _SKFChina_Common_CommunicationType_MIN, _SKFChina_Common_FUOTAType_MIN, 0, {SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_init_zero}, 0, {{{NULL}, NULL}}, {{NULL}, NULL}, false, _SKFChina_Common_Encryption_MIN, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, _SKFChina_Common_FileType_MIN, 0, _SKFChina_Common_CommunicationType_MIN, 0, {SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_init_zero}, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, false, _SKFChina_Common_Encryption_MIN, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, 0, {0}, 0, {{NULL}, NULL}, 0, false, 0}
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, 0, 0, false, 0, 0, {0}}

/* Field tags (for use in manual encoding/decoding) */
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_fuota_task_id_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_update_time_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_update_method_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_update_type_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_update_image_size_bytes_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_payload_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_is_big_endian_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_hardware_type_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_hardware_version_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_firmware_version_tag 6
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_build_id_tag 7
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_current_version_supplementary_update_info_tag 8
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_is_big_endian_tag 9
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_hardware_type_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_hardware_version_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_firmware_version_tag 6
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_build_id_tag 7
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_last_update_supplementary_info_tag 8
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_is_big_endian_tag 9
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_update_status_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_fuota_task_id_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_received_bytes_tag 6
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_debug_messages_tag 7
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_is_big_endian_tag 8
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_url_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_url_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_mqtt_topic_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_TODO_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_isBLEUart_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fuota_task_id_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_target_hardware_type_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_target_hardware_version_tag 6
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_firmware_version_tag 7
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_build_id_tag 8
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_force_fuota_tag 9
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_update_method_tag 10
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_update_type_tag 11
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fuota_with_http_tag 12
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fuota_with_froto_over_mqtt_tag 13
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fuota_with_froto_over_ble_ots_tag 14
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_md5_value_tag 15
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_sha1_value_tag 19
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_elf_hash_value_tag 20
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_supplementary_info_tag 16
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_encryp_tag 17
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_is_big_endian_tag 18
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_file_type_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_task_id_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_update_method_tag 6
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_fuota_with_http_tag 7
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_fuota_with_froto_over_mqtt_tag 8
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_fuota_with_froto_over_ble_ots_tag 9
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_supplementary_info_tag 10
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_md5_value_tag 11
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_sha1_value_tag 12
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_elf_hash_value_tag 13
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_encryp_tag 14
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_is_big_endian_tag 15
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_fuota_task_id_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_file_task_id_tag 9
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_offset_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_image_content_tag 6
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_hash_value_tag 7
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_is_big_endian_tag 8
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_header_tag 1
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_appVer_tag 2
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_sensor_id_tag 3
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_offset_tag 4
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size_tag 5
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_is_big_endian_tag 6
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_fuota_task_id_tag 7
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_file_task_id_tag 8

/* Struct field encoding specification for nanopb */
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   fuota_task_id,     1) \
X(a, STATIC,   SINGULAR, UINT64,   update_time,       2) \
X(a, STATIC,   SINGULAR, UENUM,    update_method,     3) \
X(a, STATIC,   SINGULAR, UENUM,    update_type,       4) \
X(a, STATIC,   SINGULAR, UINT32,   update_image_size_bytes,   5)
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_CALLBACK NULL
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_DEFAULT NULL

#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    payload,           4) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     5)
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_header_MSGTYPE SKFChina_Froto_FrotoHeader

#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    hardware_type,     4) \
X(a, STATIC,   SINGULAR, UINT32,   hardware_version,   5) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_version,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   build_id,          7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  current_version_supplementary_update_info,   8) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     9)
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_current_version_supplementary_update_info_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo

#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    hardware_type,     4) \
X(a, STATIC,   SINGULAR, UINT32,   hardware_version,   5) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_version,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   build_id,          7) \
X(a, STATIC,   OPTIONAL, MESSAGE,  last_update_supplementary_info,   8) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     9)
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_last_update_supplementary_info_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo

#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    update_status,     4) \
X(a, STATIC,   SINGULAR, UINT32,   fuota_task_id,     5) \
X(a, STATIC,   SINGULAR, UINT32,   received_bytes,    6) \
X(a, CALLBACK, OPTIONAL, BYTES,    debug_messages,    7) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     8)
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_header_MSGTYPE SKFChina_Froto_FrotoHeader

#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    url,               1)
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_DEFAULT NULL

#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    url,               1) \
X(a, CALLBACK, SINGULAR, BYTES,    mqtt_topic,        2)
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_DEFAULT NULL

#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_FIELDLIST(X, a) \
X(a, CALLBACK, SINGULAR, BYTES,    TODO,              1) \
X(a, STATIC,   SINGULAR, BOOL,     isBLEUart,         2)
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_DEFAULT NULL

#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UINT32,   fuota_task_id,     4) \
X(a, STATIC,   SINGULAR, UENUM,    target_hardware_type,   5) \
X(a, STATIC,   SINGULAR, UINT32,   target_hardware_version,   6) \
X(a, STATIC,   SINGULAR, UINT32,   firmware_version,   7) \
X(a, STATIC,   OPTIONAL, UINT32,   build_id,          8) \
X(a, STATIC,   SINGULAR, BOOL,     force_fuota,       9) \
X(a, STATIC,   SINGULAR, UENUM,    update_method,    10) \
X(a, STATIC,   SINGULAR, UENUM,    update_type,      11) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fuota_method,fuota_with_http,fuota_method.fuota_with_http),  12) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fuota_method,fuota_with_froto_over_mqtt,fuota_method.fuota_with_froto_over_mqtt),  13) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fuota_method,fuota_with_froto_over_ble_ots,fuota_method.fuota_with_froto_over_ble_ots),  14) \
X(a, CALLBACK, ONEOF,    BYTES,    (check_value,md5_value,check_value.md5_value),  15) \
X(a, CALLBACK, OPTIONAL, BYTES,    supplementary_info,  16) \
X(a, STATIC,   OPTIONAL, UENUM,    encryp,           17) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,    18) \
X(a, CALLBACK, ONEOF,    BYTES,    (check_value,sha1_value,check_value.sha1_value),  19) \
X(a, STATIC,   ONEOF,    UINT32,   (check_value,elf_hash_value,check_value.elf_hash_value),  20)
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fuota_method_fuota_with_http_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fuota_method_fuota_with_froto_over_mqtt_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fuota_method_fuota_with_froto_over_ble_ots_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts

#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UENUM,    file_type,         4) \
X(a, STATIC,   SINGULAR, UINT32,   task_id,           5) \
X(a, STATIC,   SINGULAR, UENUM,    update_method,     6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fuota_method,fuota_with_http,fuota_method.fuota_with_http),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fuota_method,fuota_with_froto_over_mqtt,fuota_method.fuota_with_froto_over_mqtt),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (fuota_method,fuota_with_froto_over_ble_ots,fuota_method.fuota_with_froto_over_ble_ots),   9) \
X(a, CALLBACK, OPTIONAL, BYTES,    supplementary_info,  10) \
X(a, CALLBACK, ONEOF,    BYTES,    (check_value,md5_value,check_value.md5_value),  11) \
X(a, CALLBACK, ONEOF,    BYTES,    (check_value,sha1_value,check_value.sha1_value),  12) \
X(a, STATIC,   ONEOF,    UINT32,   (check_value,elf_hash_value,check_value.elf_hash_value),  13) \
X(a, STATIC,   OPTIONAL, UENUM,    encryp,           14) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,    15)
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_fuota_method_fuota_with_http_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_fuota_method_fuota_with_froto_over_mqtt_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_fuota_method_fuota_with_froto_over_ble_ots_MSGTYPE SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts

#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   ONEOF,    UINT32,   (task_id,fuota_task_id,task_id.fuota_task_id),   4) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            5) \
X(a, CALLBACK, SINGULAR, BYTES,    image_content,     6) \
X(a, STATIC,   SINGULAR, UINT32,   hash_value,        7) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     8) \
X(a, STATIC,   ONEOF,    UINT32,   (task_id,file_task_id,task_id.file_task_id),   9)
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_header_MSGTYPE SKFChina_Froto_FrotoHeader

#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, STATIC,   SINGULAR, UINT32,   offset,            4) \
X(a, STATIC,   SINGULAR, UINT32,   size,              5) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     6) \
X(a, STATIC,   ONEOF,    UINT32,   (task_id,fuota_task_id,task_id.fuota_task_id),   7) \
X(a, STATIC,   ONEOF,    UINT32,   (task_id,file_task_id,task_id.file_task_id),   8)
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_CALLBACK pb_default_field_callback
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_DEFAULT NULL
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_header_MSGTYPE SKFChina_Froto_FrotoHeader

extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_msg;
extern const pb_msgdesc_t SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_fields &SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_msg
#define SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_fields &SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_msg
#define SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_fields &SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_msg
#define SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_fields &SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_msg
#define SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_fields &SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_msg
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_fields &SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_msg
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_fields &SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_msg
#define SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_fields &SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_msg
#define SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_fields &SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_msg
#define SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_fields &SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_msg
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_fields &SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_msg
#define SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_fields &SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_msg

/* Maximum encoded size of messages (where known) */
/* SKFChina_FirmwareUpdateOverTheAir_VersionRetrieve_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_CurrentVersionUpload_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_LastFUOTAUpload_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_UpdateStatusUpload_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_FUOTAWithHttp_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverMqtt_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_FUOTAWithFrotoOverBLEOts_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_FUOTANotifiyDisseminate_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_FileNotifiyDisseminate_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_ImageBlockDisseminate_size depends on runtime parameters */
/* SKFChina_FirmwareUpdateOverTheAir_ImageBlockRequest_size depends on runtime parameters */
#define SKFChina_FirmwareUpdateOverTheAir_UpdateTaskSupplementaryInfo_size 27

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
