/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SKFCHINA_FROTO_FROTO_PB_H_INCLUDED
#define PB_SKFCHINA_FROTO_FROTO_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Type of primitives */
typedef enum _SKFChina_Froto_FrotoPmtType { /* 0 - 10 used */
    SKFChina_Froto_FrotoPmtType_UNKNOWN_PRIMITIVETYPE = 0,
    SKFChina_Froto_FrotoPmtType_SIMPLE_UPLOAD = 1,
    SKFChina_Froto_FrotoPmtType_RELIABLE_UPLOAD = 2,
    SKFChina_Froto_FrotoPmtType_SIMPLE_DISSEMINATE = 3,
    SKFChina_Froto_FrotoPmtType_RELIABLE_DISSEMINATE = 4,
    SKFChina_Froto_FrotoPmtType_SIMPLE_BULK_UPLOAD = 5,
    SKFChina_Froto_FrotoPmtType_RELIABLE_BULK_UPLOAD = 6,
    SKFChina_Froto_FrotoPmtType_SIMPLE_BULK_DISSEMINATE = 7,
    SKFChina_Froto_FrotoPmtType_RELIABLE_BULK_DISSEMINATE = 8,
    SKFChina_Froto_FrotoPmtType_SIMPLE_REQUEST = 9,
    SKFChina_Froto_FrotoPmtType_SIMPLE_RETRIVE = 10
} SKFChina_Froto_FrotoPmtType;

/* Type of messages */
typedef enum _SKFChina_Froto_FrotoMsgType { /* 0 - 6 used */
    SKFChina_Froto_FrotoMsgType_UNKNOWN_MESSAGETYPE = 0,
    SKFChina_Froto_FrotoMsgType_NORMAL_MESSAGE = 1,
    SKFChina_Froto_FrotoMsgType_ACK_MESSAGE = 2,
    SKFChina_Froto_FrotoMsgType_REQUEST_MESSAGE = 3,
    SKFChina_Froto_FrotoMsgType_REQUEST_REPLY_MESSAGE = 4,
    SKFChina_Froto_FrotoMsgType_RETRIVE_MESSAGE = 5,
    SKFChina_Froto_FrotoMsgType_RETRIVE_REPLY_MESSAGE = 6
} SKFChina_Froto_FrotoMsgType;

/* Struct definitions */
typedef struct _SKFChina_Froto_SeqNoElement {
    /* In the current design: field number 1 has been used. */
    uint32_t seqNo;
} SKFChina_Froto_SeqNoElement;

/* Froto Header */
typedef struct _SKFChina_Froto_FrotoHeader { /* In the current design: field numbers 1 - 18 have been used. */
    /* Froto version: so far supported version is 1 */
    uint32_t version;
    /* The sensor ID */
    pb_callback_t sensor_id;
    pb_size_t which_peer_addr;
    union {
        pb_callback_t cloud_url; /* Deprecated: to save bytes and would not be used in the future */
        pb_callback_t gateway_id;
        pb_callback_t mobile_id;
        bool cloud; /* The value is true (just to indicate a message to/from cloud) */
    } peer_addr;
    /* is_up: true representing a up message from the sensor to the peer (e.g., the cloud)
 Otherwise representing a down message from the peer to the sensor
 This field is for debugging: ones can use this field to recognize the packet direction by using 
 debug tools (e.g., an MQTT broker or BLE sniffer) */
    bool is_up;
    /* The sequence number of the message: cyclic increasing 1 for each message
 For reply or acknolegement: the sequence number increases the received sequence number by 1 */
    uint32_t message_seq_no;
    /* Time to live of the message: a downcounter to indicate how many attempts remain
 If the message is sent for the first time, time_to_live is the max attempts.
 If the message is repeated, @p message_seq_no also should increase by 1 and @p time_to_live 
 should decrease by 1.
 [default = 3] */
    uint32_t time_to_live;
    /* The primitive type: indicating which primitive this message belongs to
 [default = SIMPLE_UPLOAD] */
    SKFChina_Froto_FrotoPmtType primitive_type;
    /* The message type: indicating which type message is in the primitive
 [default = NORMAL_MESSAGE] */
    SKFChina_Froto_FrotoMsgType message_type;
    /* The number of total blocks: used for large object transfer (i.e., the packet split case)
 Set to 1 if no packet split.
 [default = 1] */
    uint32_t total_block;
    /* The ack indicator: to indicate which packets have been received (only valid when
 @p message_type is @p ACK_MESSAGE)
 If this field is not included, an acknowledgement message indicates that message of 
 (@p message_seq_no - 1) is received
 acked_message_seq_no would be deprecated due to the incompatibility with nanopb-based C language
 implementation.
 Recommand using acked_message_seq_number. */
    pb_callback_t acked_message_seq_no; /* Deprecated */
    /* For @p RELIABLE_BULK_UPLOAD and @p RELIABLE_BULK_DISSEMINATE, @p ack_window defines at most 
 how many packets sent should have an acknowledgement. 
 For instance, for @p RELIABLE_BULK_UPLOAD, and @p ack_window is set to 5, if there is no acknowledgement
 received after five uplooading packets sent, then the sending failed and the five packets would be repeated
 again.
 [default = 1] */
    bool has_ack_window_size_message;
    uint32_t ack_window_size_message;
    /* The ID of a long packet: recommand to use the messaeg_seq_no of the first block of a long packet as the ID 
 of a long packet, only required in the packet split case */
    uint32_t long_packet_id;
    /* The current blocks: only required in the packet split case */
    bool has_current_block;
    uint32_t current_block;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
    pb_callback_t acked_message_seq_number;
} SKFChina_Froto_FrotoHeader;

/* The acknowledgement message independent of applications */
typedef struct _SKFChina_Froto_FrotoAckMsg { /* In the current design: field number 1 has been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header; /* Froto version */
} SKFChina_Froto_FrotoAckMsg;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _SKFChina_Froto_FrotoPmtType_MIN SKFChina_Froto_FrotoPmtType_UNKNOWN_PRIMITIVETYPE
#define _SKFChina_Froto_FrotoPmtType_MAX SKFChina_Froto_FrotoPmtType_SIMPLE_RETRIVE
#define _SKFChina_Froto_FrotoPmtType_ARRAYSIZE ((SKFChina_Froto_FrotoPmtType)(SKFChina_Froto_FrotoPmtType_SIMPLE_RETRIVE+1))

#define _SKFChina_Froto_FrotoMsgType_MIN SKFChina_Froto_FrotoMsgType_UNKNOWN_MESSAGETYPE
#define _SKFChina_Froto_FrotoMsgType_MAX SKFChina_Froto_FrotoMsgType_RETRIVE_REPLY_MESSAGE
#define _SKFChina_Froto_FrotoMsgType_ARRAYSIZE ((SKFChina_Froto_FrotoMsgType)(SKFChina_Froto_FrotoMsgType_RETRIVE_REPLY_MESSAGE+1))


#define SKFChina_Froto_FrotoHeader_primitive_type_ENUMTYPE SKFChina_Froto_FrotoPmtType
#define SKFChina_Froto_FrotoHeader_message_type_ENUMTYPE SKFChina_Froto_FrotoMsgType



/* Initializer values for message structs */
#define SKFChina_Froto_SeqNoElement_init_default {0}
#define SKFChina_Froto_FrotoHeader_init_default  {0, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, 0, 0, 0, _SKFChina_Froto_FrotoPmtType_MIN, _SKFChina_Froto_FrotoMsgType_MIN, 0, {{NULL}, NULL}, false, 0, 0, false, 0, false, 0, {{NULL}, NULL}}
#define SKFChina_Froto_FrotoAckMsg_init_default  {false, SKFChina_Froto_FrotoHeader_init_default}
#define SKFChina_Froto_SeqNoElement_init_zero    {0}
#define SKFChina_Froto_FrotoHeader_init_zero     {0, {{NULL}, NULL}, 0, {{{NULL}, NULL}}, 0, 0, 0, _SKFChina_Froto_FrotoPmtType_MIN, _SKFChina_Froto_FrotoMsgType_MIN, 0, {{NULL}, NULL}, false, 0, 0, false, 0, false, 0, {{NULL}, NULL}}
#define SKFChina_Froto_FrotoAckMsg_init_zero     {false, SKFChina_Froto_FrotoHeader_init_zero}

/* Field tags (for use in manual encoding/decoding) */
#define SKFChina_Froto_SeqNoElement_seqNo_tag    1
#define SKFChina_Froto_FrotoHeader_version_tag   1
#define SKFChina_Froto_FrotoHeader_sensor_id_tag 2
#define SKFChina_Froto_FrotoHeader_cloud_url_tag 3
#define SKFChina_Froto_FrotoHeader_gateway_id_tag 4
#define SKFChina_Froto_FrotoHeader_mobile_id_tag 5
#define SKFChina_Froto_FrotoHeader_cloud_tag     15
#define SKFChina_Froto_FrotoHeader_is_up_tag     6
#define SKFChina_Froto_FrotoHeader_message_seq_no_tag 7
#define SKFChina_Froto_FrotoHeader_time_to_live_tag 8
#define SKFChina_Froto_FrotoHeader_primitive_type_tag 9
#define SKFChina_Froto_FrotoHeader_message_type_tag 10
#define SKFChina_Froto_FrotoHeader_total_block_tag 11
#define SKFChina_Froto_FrotoHeader_acked_message_seq_no_tag 12
#define SKFChina_Froto_FrotoHeader_ack_window_size_message_tag 13
#define SKFChina_Froto_FrotoHeader_long_packet_id_tag 14
#define SKFChina_Froto_FrotoHeader_current_block_tag 16
#define SKFChina_Froto_FrotoHeader_is_big_endian_tag 17
#define SKFChina_Froto_FrotoHeader_acked_message_seq_number_tag 18
#define SKFChina_Froto_FrotoAckMsg_header_tag    1

/* Struct field encoding specification for nanopb */
#define SKFChina_Froto_SeqNoElement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   seqNo,             1)
#define SKFChina_Froto_SeqNoElement_CALLBACK NULL
#define SKFChina_Froto_SeqNoElement_DEFAULT NULL

#define SKFChina_Froto_FrotoHeader_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   version,           1) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         2) \
X(a, CALLBACK, ONEOF,    BYTES,    (peer_addr,cloud_url,peer_addr.cloud_url),   3) \
X(a, CALLBACK, ONEOF,    BYTES,    (peer_addr,gateway_id,peer_addr.gateway_id),   4) \
X(a, CALLBACK, ONEOF,    BYTES,    (peer_addr,mobile_id,peer_addr.mobile_id),   5) \
X(a, STATIC,   SINGULAR, BOOL,     is_up,             6) \
X(a, STATIC,   SINGULAR, UINT32,   message_seq_no,    7) \
X(a, STATIC,   SINGULAR, UINT32,   time_to_live,      8) \
X(a, STATIC,   SINGULAR, UENUM,    primitive_type,    9) \
X(a, STATIC,   SINGULAR, UENUM,    message_type,     10) \
X(a, STATIC,   SINGULAR, UINT32,   total_block,      11) \
X(a, CALLBACK, REPEATED, UINT32,   acked_message_seq_no,  12) \
X(a, STATIC,   OPTIONAL, UINT32,   ack_window_size_message,  13) \
X(a, STATIC,   SINGULAR, UINT32,   long_packet_id,   14) \
X(a, STATIC,   ONEOF,    BOOL,     (peer_addr,cloud,peer_addr.cloud),  15) \
X(a, STATIC,   OPTIONAL, UINT32,   current_block,    16) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,    17) \
X(a, CALLBACK, REPEATED, MESSAGE,  acked_message_seq_number,  18)
#define SKFChina_Froto_FrotoHeader_CALLBACK pb_default_field_callback
#define SKFChina_Froto_FrotoHeader_DEFAULT NULL
#define SKFChina_Froto_FrotoHeader_acked_message_seq_number_MSGTYPE SKFChina_Froto_SeqNoElement

#define SKFChina_Froto_FrotoAckMsg_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1)
#define SKFChina_Froto_FrotoAckMsg_CALLBACK NULL
#define SKFChina_Froto_FrotoAckMsg_DEFAULT NULL
#define SKFChina_Froto_FrotoAckMsg_header_MSGTYPE SKFChina_Froto_FrotoHeader

extern const pb_msgdesc_t SKFChina_Froto_SeqNoElement_msg;
extern const pb_msgdesc_t SKFChina_Froto_FrotoHeader_msg;
extern const pb_msgdesc_t SKFChina_Froto_FrotoAckMsg_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKFChina_Froto_SeqNoElement_fields &SKFChina_Froto_SeqNoElement_msg
#define SKFChina_Froto_FrotoHeader_fields &SKFChina_Froto_FrotoHeader_msg
#define SKFChina_Froto_FrotoAckMsg_fields &SKFChina_Froto_FrotoAckMsg_msg

/* Maximum encoded size of messages (where known) */
/* SKFChina_Froto_FrotoHeader_size depends on runtime parameters */
/* SKFChina_Froto_FrotoAckMsg_size depends on runtime parameters */
#define SKFChina_Froto_SeqNoElement_size         6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
