/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "Froto.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SKFChina_Froto_SeqNoElement, SKFChina_Froto_SeqNoElement, AUTO)


PB_BIND(SKFChina_Froto_FrotoHeader, SKFChina_Froto_FrotoHeader, AUTO)


PB_BIND(SKFChina_Froto_FrotoAckMsg, SKFChina_Froto_FrotoAckMsg, AUTO)





