/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.7 */

#ifndef PB_SKFCHINA_SENSINGDATAUPLOAD_SENSINGDATAUPLOAD_PB_H_INCLUDED
#define PB_SKFCHINA_SENSINGDATAUPLOAD_SENSINGDATAUPLOAD_PB_H_INCLUDED
#include <pb.h>
#include "Common.pb.h"
#include "Froto.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
/* Alarm and notify information: event + the numbers of events over 1 month and 3 months */
typedef struct _SKFChina_SensingDataUpload_AlarmAndNotifyInfo {
    /* In the current design: field numbers 1 - 3 have been used. */
    SKFChina_Common_AlarmAndNotify measurement;
    uint32_t amount_over_30_days;
    uint32_t amount_over_90_days;
} SKFChina_SensingDataUpload_AlarmAndNotifyInfo;

/* measurement */
typedef struct _SKFChina_SensingDataUpload_Measurement { /* In the current design: field numbers 1 - 21 have been used. */
    /* The type of measurement: what the sensing data represents */
    SKFChina_Common_MeasurementType measure_type;
    /* The type of sensor: if the data is sampled by an individual sensor, this field can be filled.
 Otherwise, no need to fill this field */
    bool has_sensor;
    SKFChina_Common_SensorType sensor;
    /* The type of product */
    SKFChina_Common_ProductType product;
    /* The range of the sensor (if applicable) */
    bool has_range;
    SKFChina_Common_Range range;
    /* The unit of the data */
    bool has_unit;
    SKFChina_Common_Unit unit;
    /* The length (points) of a measurement: how many points are in this measurement
 For instance, given a measurement of @p TEMPERATURE_CURRENT,  @p measure_length is 1 because 
 there is only one temperature point.
 Given a measurement of @p VIBRATION_ENV3_RMS, @p measure_length is the length of the vibration
 measurement rather than the length of the rms (i.e., 1 byte). */
    bool has_measure_length_sample;
    uint32_t measure_length_sample;
    /* The length (points) of the data: how many points are in the uploaded data totally (not just the current packets)
 For instance, for a measurement of @p TEMPERATURE_HISTORY, @p measure_length is 1 but @p total_data_length
 is the total length of the history (e.g., 256 history temperature sample points) even the history requires packet
 split. */
    bool has_total_data_length_sample;
    uint32_t total_data_length_sample;
    /* The sequence number of a measurement: cyclic increasing 1 for each measurement.
 For instance, a sensor performs a vibration measurement and based on this measurement env 3 is calculated.
 In this case, @p VIBRATION_ACC_WAVE and @p VIBRATION_ENV3_WAVE have the same @p measure_seq_no. */
    uint32_t measure_seq_no;
    /* The data format: for instance, uint32_t or int16_t. */
    SKFChina_Common_Format data_format;
    /* check value of the whole data (if the data is sent with multiple packets). */
    bool has_crc32_value;
    uint32_t crc32_value;
    /* Encryption: indicate which encryption is adopted for @p Data.data. */
    bool has_encryp;
    SKFChina_Common_Encryption encryp;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The moment of measurement (unix timestamp, 0 time zone, unit is ms) */
    uint64_t sample_time;
    /* Memory ID */
    bool has_memory_id;
    int32_t memory_id;
    /* This field is required only if it is an alarm or notification */
    bool has_alarm_or_notify;
    SKFChina_SensingDataUpload_AlarmAndNotifyInfo alarm_or_notify;
    /* Sample rate (in Hz) of the data (e.g., vibration) */
    bool has_sample_rate_hz;
    float sample_rate_hz;
    /* Sample period (in S) of the data (e.g., temperature) */
    bool has_sample_period_s;
    uint32_t sample_period_s;
    /* Dimension mask to indicate which axis (or axes) used£ºSKFChina.Common.Dimension */
    bool has_dimension;
    uint32_t dimension;
    /* Communication stuffs: if measure_type is a communication-related metric, then the followings are expected
 For the devices with BLE or IEEE 802.15.4 transceivers */
    pb_callback_t mac_address;
    /* For the devices with cellular modules */
    pb_callback_t iccid;
    /* For the devices with cellular modules */
    pb_callback_t imei;
} SKFChina_SensingDataUpload_Measurement;

/* Measurement data */
typedef struct _SKFChina_SensingDataUpload_Data { /* In the current design: field numbers 1 - 3 have been used. */
    /* Start point of the data: for instance, given a piece of waveform (with 256 points), this field is set to 0 for the 
 first packet. Assuming up to 128 samples can be sent within a packet, then the waveform is required packet split.
 For the sencond packet, the start point is required to set to 128, because 0th - 127th samples have already been sent. */
    uint32_t start_point;
    pb_callback_t data;
    /* check value of the data */
    uint32_t crc32_value;
} SKFChina_SensingDataUpload_Data;

/* Data pair: Measurement + Data */
typedef struct _SKFChina_SensingDataUpload_DataPair { /* In the current design: field numbers 1 - 2 have been used. */
    /* For long data (i.e., packet split is required), only the first packet, @p measurement is required
 For short data (i.e., no packet split is required), @p measurement is required */
    bool has_measurement;
    SKFChina_SensingDataUpload_Measurement measurement;
    bool has_measurement_data;
    SKFChina_SensingDataUpload_Data measurement_data;
} SKFChina_SensingDataUpload_DataPair;

typedef struct _SKFChina_SensingDataUpload_MeasurementTypeMsg {
    /* In the current design: field numbers 1 - 2 have been used. */
    SKFChina_Common_MeasurementType measure_type;
    /* Dimension mask to indicate which axis (or axes) used£ºSKFChina.Common.Dimension */
    bool has_dimension;
    uint32_t dimension;
} SKFChina_SensingDataUpload_MeasurementTypeMsg;

typedef struct _SKFChina_SensingDataUpload_SensorTypeMsg {
    /* In the current design: field numbers 1 has been used. */
    SKFChina_Common_SensorType sensor;
} SKFChina_SensingDataUpload_SensorTypeMsg;

/* To select data (of given measurement type, given period, and given sensor), 
 then the sensor would upload them
 If @p sample_time_start and @p sample_time_end are both set to zeros, no selection is enabled. */
typedef struct _SKFChina_SensingDataUpload_DataSelectionDisseminate { /* In the current design: field numbers 1 - 9 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* The sensor ID: considering future applications with a gateway */
    pb_callback_t sensor_id;
    /* The type of measurement */
    pb_callback_t measure_type;
    /* The type of sensor: if the data is sampled by sensors (not fused data), this field can be filled.
 Otherwise, no need to fill this field */
    pb_callback_t sensor;
    /* The type of product */
    SKFChina_Common_ProductType product;
    /* The data is sampled in the time [sample_time_start, sample_time_end] */
    uint64_t sample_time_start;
    uint64_t sample_time_end;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
} SKFChina_SensingDataUpload_DataSelectionDisseminate;

/* Sensing data uploading message (according to data selection)
 For a long payload (e.g., a piece of waveform), one can send a @p measurement first to notify the peer what the 
 following data is. Then, multiple @p measurement_data can be sent. The fields (i.e., @p total_block and 
 @p current_blocks) in @p header can be used to indicate how to recover the payload when multiple (splitted)
 packets received. */
typedef struct _SKFChina_SensingDataUpload_DataUpload { /* In the current design: field numbers 1 - 4 have been used. */
    bool has_header;
    SKFChina_Froto_FrotoHeader header;
    /* Application version: so far the supported version is 1 */
    uint32_t appVer;
    /* True if big endian
 Little endian used if this field is abscent */
    bool has_is_big_endian;
    bool is_big_endian;
    /* Data: can be multiple types of measurement */
    pb_callback_t data_pair;
} SKFChina_SensingDataUpload_DataUpload;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_init_default {_SKFChina_Common_AlarmAndNotify_MIN, 0, 0}
#define SKFChina_SensingDataUpload_Measurement_init_default {_SKFChina_Common_MeasurementType_MIN, false, _SKFChina_Common_SensorType_MIN, _SKFChina_Common_ProductType_MIN, false, _SKFChina_Common_Range_MIN, false, _SKFChina_Common_Unit_MIN, false, 0, false, 0, 0, _SKFChina_Common_Format_MIN, false, 0, false, _SKFChina_Common_Encryption_MIN, {{NULL}, NULL}, 0, false, 0, false, SKFChina_SensingDataUpload_AlarmAndNotifyInfo_init_default, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SKFChina_SensingDataUpload_Data_init_default {0, {{NULL}, NULL}, 0}
#define SKFChina_SensingDataUpload_DataPair_init_default {false, SKFChina_SensingDataUpload_Measurement_init_default, false, SKFChina_SensingDataUpload_Data_init_default}
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_init_default {_SKFChina_Common_MeasurementType_MIN, false, 0}
#define SKFChina_SensingDataUpload_SensorTypeMsg_init_default {_SKFChina_Common_SensorType_MIN}
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, 0, 0, false, 0}
#define SKFChina_SensingDataUpload_DataUpload_init_default {false, SKFChina_Froto_FrotoHeader_init_default, 0, false, 0, {{NULL}, NULL}}
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_init_zero {_SKFChina_Common_AlarmAndNotify_MIN, 0, 0}
#define SKFChina_SensingDataUpload_Measurement_init_zero {_SKFChina_Common_MeasurementType_MIN, false, _SKFChina_Common_SensorType_MIN, _SKFChina_Common_ProductType_MIN, false, _SKFChina_Common_Range_MIN, false, _SKFChina_Common_Unit_MIN, false, 0, false, 0, 0, _SKFChina_Common_Format_MIN, false, 0, false, _SKFChina_Common_Encryption_MIN, {{NULL}, NULL}, 0, false, 0, false, SKFChina_SensingDataUpload_AlarmAndNotifyInfo_init_zero, false, 0, false, 0, false, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}}
#define SKFChina_SensingDataUpload_Data_init_zero {0, {{NULL}, NULL}, 0}
#define SKFChina_SensingDataUpload_DataPair_init_zero {false, SKFChina_SensingDataUpload_Measurement_init_zero, false, SKFChina_SensingDataUpload_Data_init_zero}
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_init_zero {_SKFChina_Common_MeasurementType_MIN, false, 0}
#define SKFChina_SensingDataUpload_SensorTypeMsg_init_zero {_SKFChina_Common_SensorType_MIN}
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, {{NULL}, NULL}, {{NULL}, NULL}, {{NULL}, NULL}, _SKFChina_Common_ProductType_MIN, 0, 0, false, 0}
#define SKFChina_SensingDataUpload_DataUpload_init_zero {false, SKFChina_Froto_FrotoHeader_init_zero, 0, false, 0, {{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_measurement_tag 1
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_amount_over_30_days_tag 2
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_amount_over_90_days_tag 3
#define SKFChina_SensingDataUpload_Measurement_measure_type_tag 1
#define SKFChina_SensingDataUpload_Measurement_sensor_tag 2
#define SKFChina_SensingDataUpload_Measurement_product_tag 3
#define SKFChina_SensingDataUpload_Measurement_range_tag 4
#define SKFChina_SensingDataUpload_Measurement_unit_tag 5
#define SKFChina_SensingDataUpload_Measurement_measure_length_sample_tag 6
#define SKFChina_SensingDataUpload_Measurement_total_data_length_sample_tag 7
#define SKFChina_SensingDataUpload_Measurement_measure_seq_no_tag 8
#define SKFChina_SensingDataUpload_Measurement_data_format_tag 9
#define SKFChina_SensingDataUpload_Measurement_crc32_value_tag 10
#define SKFChina_SensingDataUpload_Measurement_encryp_tag 11
#define SKFChina_SensingDataUpload_Measurement_sensor_id_tag 12
#define SKFChina_SensingDataUpload_Measurement_sample_time_tag 13
#define SKFChina_SensingDataUpload_Measurement_memory_id_tag 14
#define SKFChina_SensingDataUpload_Measurement_alarm_or_notify_tag 15
#define SKFChina_SensingDataUpload_Measurement_sample_rate_hz_tag 16
#define SKFChina_SensingDataUpload_Measurement_sample_period_s_tag 17
#define SKFChina_SensingDataUpload_Measurement_dimension_tag 18
#define SKFChina_SensingDataUpload_Measurement_mac_address_tag 19
#define SKFChina_SensingDataUpload_Measurement_iccid_tag 20
#define SKFChina_SensingDataUpload_Measurement_imei_tag 21
#define SKFChina_SensingDataUpload_Data_start_point_tag 1
#define SKFChina_SensingDataUpload_Data_data_tag 2
#define SKFChina_SensingDataUpload_Data_crc32_value_tag 3
#define SKFChina_SensingDataUpload_DataPair_measurement_tag 1
#define SKFChina_SensingDataUpload_DataPair_measurement_data_tag 2
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_measure_type_tag 1
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_dimension_tag 2
#define SKFChina_SensingDataUpload_SensorTypeMsg_sensor_tag 1
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_header_tag 1
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_appVer_tag 2
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_sensor_id_tag 3
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_measure_type_tag 4
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_sensor_tag 5
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_product_tag 6
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_sample_time_start_tag 7
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_sample_time_end_tag 8
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_is_big_endian_tag 9
#define SKFChina_SensingDataUpload_DataUpload_header_tag 1
#define SKFChina_SensingDataUpload_DataUpload_appVer_tag 2
#define SKFChina_SensingDataUpload_DataUpload_is_big_endian_tag 3
#define SKFChina_SensingDataUpload_DataUpload_data_pair_tag 4

/* Struct field encoding specification for nanopb */
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    measurement,       1) \
X(a, STATIC,   SINGULAR, UINT32,   amount_over_30_days,   2) \
X(a, STATIC,   SINGULAR, UINT32,   amount_over_90_days,   3)
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_CALLBACK NULL
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_DEFAULT NULL

#define SKFChina_SensingDataUpload_Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    measure_type,      1) \
X(a, STATIC,   OPTIONAL, UENUM,    sensor,            2) \
X(a, STATIC,   SINGULAR, UENUM,    product,           3) \
X(a, STATIC,   OPTIONAL, UENUM,    range,             4) \
X(a, STATIC,   OPTIONAL, UENUM,    unit,              5) \
X(a, STATIC,   OPTIONAL, UINT32,   measure_length_sample,   6) \
X(a, STATIC,   OPTIONAL, UINT32,   total_data_length_sample,   7) \
X(a, STATIC,   SINGULAR, UINT32,   measure_seq_no,    8) \
X(a, STATIC,   SINGULAR, UENUM,    data_format,       9) \
X(a, STATIC,   OPTIONAL, UINT32,   crc32_value,      10) \
X(a, STATIC,   OPTIONAL, UENUM,    encryp,           11) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,        12) \
X(a, STATIC,   SINGULAR, UINT64,   sample_time,      13) \
X(a, STATIC,   OPTIONAL, INT32,    memory_id,        14) \
X(a, STATIC,   OPTIONAL, MESSAGE,  alarm_or_notify,  15) \
X(a, STATIC,   OPTIONAL, FLOAT,    sample_rate_hz,   16) \
X(a, STATIC,   OPTIONAL, UINT32,   sample_period_s,  17) \
X(a, STATIC,   OPTIONAL, UINT32,   dimension,        18) \
X(a, CALLBACK, OPTIONAL, BYTES,    mac_address,      19) \
X(a, CALLBACK, OPTIONAL, BYTES,    iccid,            20) \
X(a, CALLBACK, OPTIONAL, BYTES,    imei,             21)
#define SKFChina_SensingDataUpload_Measurement_CALLBACK pb_default_field_callback
#define SKFChina_SensingDataUpload_Measurement_DEFAULT NULL
#define SKFChina_SensingDataUpload_Measurement_alarm_or_notify_MSGTYPE SKFChina_SensingDataUpload_AlarmAndNotifyInfo

#define SKFChina_SensingDataUpload_Data_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   start_point,       1) \
X(a, CALLBACK, SINGULAR, BYTES,    data,              2) \
X(a, STATIC,   SINGULAR, UINT32,   crc32_value,       3)
#define SKFChina_SensingDataUpload_Data_CALLBACK pb_default_field_callback
#define SKFChina_SensingDataUpload_Data_DEFAULT NULL

#define SKFChina_SensingDataUpload_DataPair_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  measurement,       1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  measurement_data,   2)
#define SKFChina_SensingDataUpload_DataPair_CALLBACK NULL
#define SKFChina_SensingDataUpload_DataPair_DEFAULT NULL
#define SKFChina_SensingDataUpload_DataPair_measurement_MSGTYPE SKFChina_SensingDataUpload_Measurement
#define SKFChina_SensingDataUpload_DataPair_measurement_data_MSGTYPE SKFChina_SensingDataUpload_Data

#define SKFChina_SensingDataUpload_MeasurementTypeMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    measure_type,      1) \
X(a, STATIC,   OPTIONAL, UINT32,   dimension,         2)
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_CALLBACK NULL
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_DEFAULT NULL

#define SKFChina_SensingDataUpload_SensorTypeMsg_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    sensor,            1)
#define SKFChina_SensingDataUpload_SensorTypeMsg_CALLBACK NULL
#define SKFChina_SensingDataUpload_SensorTypeMsg_DEFAULT NULL

#define SKFChina_SensingDataUpload_DataSelectionDisseminate_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, CALLBACK, SINGULAR, BYTES,    sensor_id,         3) \
X(a, CALLBACK, REPEATED, MESSAGE,  measure_type,      4) \
X(a, CALLBACK, REPEATED, MESSAGE,  sensor,            5) \
X(a, STATIC,   SINGULAR, UENUM,    product,           6) \
X(a, STATIC,   SINGULAR, UINT64,   sample_time_start,   7) \
X(a, STATIC,   SINGULAR, UINT64,   sample_time_end,   8) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     9)
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_CALLBACK pb_default_field_callback
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_DEFAULT NULL
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_measure_type_MSGTYPE SKFChina_SensingDataUpload_MeasurementTypeMsg
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_sensor_MSGTYPE SKFChina_SensingDataUpload_SensorTypeMsg

#define SKFChina_SensingDataUpload_DataUpload_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  header,            1) \
X(a, STATIC,   SINGULAR, UINT32,   appVer,            2) \
X(a, STATIC,   OPTIONAL, BOOL,     is_big_endian,     3) \
X(a, CALLBACK, REPEATED, MESSAGE,  data_pair,         4)
#define SKFChina_SensingDataUpload_DataUpload_CALLBACK pb_default_field_callback
#define SKFChina_SensingDataUpload_DataUpload_DEFAULT NULL
#define SKFChina_SensingDataUpload_DataUpload_header_MSGTYPE SKFChina_Froto_FrotoHeader
#define SKFChina_SensingDataUpload_DataUpload_data_pair_MSGTYPE SKFChina_SensingDataUpload_DataPair

extern const pb_msgdesc_t SKFChina_SensingDataUpload_AlarmAndNotifyInfo_msg;
extern const pb_msgdesc_t SKFChina_SensingDataUpload_Measurement_msg;
extern const pb_msgdesc_t SKFChina_SensingDataUpload_Data_msg;
extern const pb_msgdesc_t SKFChina_SensingDataUpload_DataPair_msg;
extern const pb_msgdesc_t SKFChina_SensingDataUpload_MeasurementTypeMsg_msg;
extern const pb_msgdesc_t SKFChina_SensingDataUpload_SensorTypeMsg_msg;
extern const pb_msgdesc_t SKFChina_SensingDataUpload_DataSelectionDisseminate_msg;
extern const pb_msgdesc_t SKFChina_SensingDataUpload_DataUpload_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_fields &SKFChina_SensingDataUpload_AlarmAndNotifyInfo_msg
#define SKFChina_SensingDataUpload_Measurement_fields &SKFChina_SensingDataUpload_Measurement_msg
#define SKFChina_SensingDataUpload_Data_fields &SKFChina_SensingDataUpload_Data_msg
#define SKFChina_SensingDataUpload_DataPair_fields &SKFChina_SensingDataUpload_DataPair_msg
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_fields &SKFChina_SensingDataUpload_MeasurementTypeMsg_msg
#define SKFChina_SensingDataUpload_SensorTypeMsg_fields &SKFChina_SensingDataUpload_SensorTypeMsg_msg
#define SKFChina_SensingDataUpload_DataSelectionDisseminate_fields &SKFChina_SensingDataUpload_DataSelectionDisseminate_msg
#define SKFChina_SensingDataUpload_DataUpload_fields &SKFChina_SensingDataUpload_DataUpload_msg

/* Maximum encoded size of messages (where known) */
/* SKFChina_SensingDataUpload_Measurement_size depends on runtime parameters */
/* SKFChina_SensingDataUpload_Data_size depends on runtime parameters */
/* SKFChina_SensingDataUpload_DataPair_size depends on runtime parameters */
/* SKFChina_SensingDataUpload_DataSelectionDisseminate_size depends on runtime parameters */
/* SKFChina_SensingDataUpload_DataUpload_size depends on runtime parameters */
#define SKFChina_SensingDataUpload_AlarmAndNotifyInfo_size 14
#define SKFChina_SensingDataUpload_MeasurementTypeMsg_size 8
#define SKFChina_SensingDataUpload_SensorTypeMsg_size 2

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
