/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "SensingDataUpload.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SKFChina_SensingDataUpload_AlarmAndNotifyInfo, SKFChina_SensingDataUpload_AlarmAndNotifyInfo, AUTO)


PB_BIND(SKFChina_SensingDataUpload_Measurement, SKFChina_SensingDataUpload_Measurement, AUTO)


PB_BIND(SKFChina_SensingDataUpload_Data, SKFChina_SensingDataUpload_Data, AUTO)


PB_BIND(SKFChina_SensingDataUpload_DataPair, SKFChina_SensingDataUpload_DataPair, 2)


PB_BIND(SKFChina_SensingDataUpload_MeasurementTypeMsg, SKFChina_SensingDataUpload_MeasurementTypeMsg, AUTO)


PB_BIND(SKFChina_SensingDataUpload_SensorTypeMsg, SKFChina_SensingDataUpload_SensorTypeMsg, AUTO)


PB_BIND(SKFChina_SensingDataUpload_DataSelectionDisseminate, SKFChina_SensingDataUpload_DataSelectionDisseminate, AUTO)


PB_BIND(SKFChina_SensingDataUpload_DataUpload, SKFChina_SensingDataUpload_DataUpload, AUTO)



