/**
 * @file    jsonName.h
 * @author  Xiaoyuan (Sean) Ma (zz2134)
 * @date    2024-04-26
 * @brief   Name used by json
 * @details
 */
#ifndef __JSONNAME_H__
#define __JSONNAME_H__

// Names used by gwConfig.json
// Root
#define GWCONFIGJSON_NAME_VERSION "version"
#define GWCONFIGJSON_NAME_LASTEDITTIME "lastEditTime"
#define GWCONFIGJSON_NAME_GWCONFIG "gwConfig"
// Root->gwConfig
#define GWCONFIGJSON_NAME_GWCONFIG_TYPE "type"
#define GWCONFIGJSON_NAME_GWCONFIG_MANUFACTURER "manufacturer"
#define GWCONFIGJSON_NAME_GWCONFIG_NAME "name"
#define GWCONFIGJSON_NAME_GWCONFIG_NAMEID "nameId"
#define GWCONFIGJSON_NAME_GWCONFIG_MACADDR "macAddr"
#define GWCONFIGJSON_NAME_GWCONFIG_GATEWAYMODE "gatewayMode"
#define GWCONFIGJSON_NAME_GWCONFIG_BLECONFIG "BLEConfig"
#define GWCONFIGJSON_NAME_GWCONFIG_TIMECONFIG "timeConfig"
#define GWCONFIGJSON_NAME_GWCONFIG_MQTTCONFIG "MQTTConfig"
#define GWCONFIGJSON_NAME_GWCONFIG_IPCONFIG "IPConfig"
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDRENNUMBER "childrenNumber"
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDREN "children"
// Root->gwConfig->BLEConfig
#define GWCONFIGJSON_NAME_GWCONFIG_BLECONFIG_BLE1TXPOWER "BLE1TxPower"
#define GWCONFIGJSON_NAME_GWCONFIG_BLECONFIG_BLE2TXPOWER "BLE2TxPower"
#define GWCONFIGJSON_NAME_GWCONFIG_BLECONFIG_BLE1ANTENNA "BLE1Antenna"
#define GWCONFIGJSON_NAME_GWCONFIG_BLECONFIG_BLE2ANTENNA "BLE2Antenna"
#define GWCONFIGJSON_NAME_GWCONFIG_BLECONFIG_BLEDUPLICATEDDROP \
  "BLEDuplicatedDrop"
// Root->gwConfig->timeConfig
#define GWCONFIGJSON_NAME_GWCONFIG_TIMECONFIG_TIMESTAMP "timeStamp"
#define GWCONFIGJSON_NAME_GWCONFIG_TIMECONFIG_TIMESETTING "timeSetting"
#define GWCONFIGJSON_NAME_GWCONFIG_TIMECONFIG_TIMENTPURL "timeNTPUrl"
// Root->gwConfig->mqttConfig
#define GWCONFIGJSON_NAME_GWCONFIG_MQTTCONFIG_MQTTSECURITYTYPE \
  "MQTTSecurityType"
#define GWCONFIGJSON_NAME_GWCONFIG_MQTTCONFIG_MQTTHOST "MQTTHost"
#define GWCONFIGJSON_NAME_GWCONFIG_MQTTCONFIG_MQTTPORT "MQTTPort"
// Root->gwConfig->ipConfig
#define GWCONFIGJSON_NAME_GWCONFIG_IPCONFIG_DHCPENABLE "DHCPEnable"
#define GWCONFIGJSON_NAME_GWCONFIG_IPCONFIG_STATICIPADDR "staticIPAddr"
#define GWCONFIGJSON_NAME_GWCONFIG_IPCONFIG_NETMASK "netMask"
#define GWCONFIGJSON_NAME_GWCONFIG_IPCONFIG_DNSSERVER "DNSServer"
#define GWCONFIGJSON_NAME_GWCONFIG_IPCONFIG_GATEWAYADDR "gatewayAddr"
// Root->gwConfig->children
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDREN_ELEMENT_TYPE "type"
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDREN_ELEMENT_MANUFACTURER \
  "manufacturer"
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDREN_ELEMENT_NAME "name"
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDREN_ELEMENT_NAMEID "nameId"
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDREN_ELEMENT_BLESENSORNAME \
  "BLESensorName"
#define GWCONFIGJSON_NAME_GWCONFIG_CHILDREN_ELEMENT_MACADDR "macAddr"

// Names used by sensorConfig.json
// Root
#define SENSORCONFIGJSON_NAME_VERSION "version"
#define SENSORCONFIGJSON_NAME_LASTEDITTIME "lastEditTime"
#define SENSORCONFIGJSON_NAME_HAVECONFIGUREDTOSENSOR \
  "haveConfiguredToSensor"
#define SENSORCONFIGJSON_NAME_WHENCONFIGUREDSENSOR "whenConfiguredToSensor"
#define SENSORCONFIGJSON_NAME_TYPE "type"
#define SENSORCONFIGJSON_NAME_MANUFACTURER "manufacturer"
#define SENSORCONFIGJSON_NAME_NAMEID "nameId"
#define SENSORCONFIGJSON_NAME_MACADDR "macAddr"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG "bulletSensorConfig"
// Root->bulletSensorConfig
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG "sysConfig"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG "scheduleConfig"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG "sensingConfig"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG "algorithmConfig"
// Root->bulletSensorConfig->sysConfig
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG_SENSORMODE \
  "sensorMode"
#if (STATUS_SENSING_FEATURE_ENABLE == 1)
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG_SENSORMODEPARAM \
  "sensorModeParameter"
#endif /* STATUS_SENSING_FEATURE_ENABLE == 1 */
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG_BATTERYALARMTHRE \
  "batteryAlarmThreshold"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG_CURRENTTIME \
  "currentTime"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG_TXPOWERADV \
  "txPower_adv"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG_DATARATEAUXADV \
  "dataRate_auxAdv"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SYSCFG_TXPOWERAUXADV \
  "txPower_auxAdv"
// Root->bulletSensorConfig->scheduleConfig
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_PERIODQUICKPOLL \
  "period_quickPolling"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_REFTIMEQUICKPOLL \
  "referenceTime_quickPolling"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_PERIODREGULARSEN \
  "period_regularSensing"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_REFTIMEREGULARSEN \
  "referenceTime_regularSensing"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_PERIODCOMM \
  "period_comm"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_REFTIMEPERIODCOMM \
  "referenceTime_period_comm"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_PERIODWAVEDATAACQ \
  "waveDataAcqPeriod"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SCHCFG_REFTIMEWAVEDATAACQ \
  "waveDataAcqReference"
// Root->bulletSensorConfig->sensingConfig
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_PREACQVIBFSHZ \
  "PRE_ACQ_VIB_FS_HZ"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_PREACQVIBN \
  "PRE_ACQ_VIB_N"
#define \
  SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_PREACQVIBAXISACQEVAL \
  "PRE_ACQ_VIB_AXIS_ACQ_EVAL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_PREACQVIBRANGE \
  "PRE_ACQ_VIB_RANGE"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_PREACQMAGFSHZ \
  "PRE_ACQ_MAG_FS_HZ"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_PREACQMAGN \
  "PRE_ACQ_MAG_N"
#define \
  SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_PREACQMAGAXISACQEVAL \
  "PRE_ACQ_MAG_AXIS_ACQ_EVAL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_FACC "Facc"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_NACC "Nacc"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_ACQVIBAXISACQEVAL \
  "ACQ_VIB_AXIS_ACQ_EVAL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_ACQVIBRANGE \
  "ACQ_VIB_RANGE"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_ACQMAGFSHZ \
  "ACQ_MAG_FS_HZ"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_ACQMAGN \
  "ACQ_MAG_N"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_ACQMAGAXISACQEVAL \
  "ACQ_MAG_AXIS_ACQ_EVAL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_SENCFG_FSCOEF "FS_COEF"
// Root->bulletSensorConfig->algorithmConfig
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_GEECOEF \
  "GEE_COEF"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_VCOEF \
  "V_COEF"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MEASPOSITION \
  "MEAS_POSITION"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MEASLOAD \
  "MEAS_LOAD"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MEASAXISVIB \
  "MEAS_AXIS_VIB"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MEASAXISMAG \
  "MEAS_AXIS_MAG"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_VIBSTARTFG \
  "VIB_START_FG"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_VIBRMSSTARTTL \
  "VIB_RMS_START_TL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MAGSTARTFG \
  "MAG_START_FG"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MAGRMSSTARTTL \
  "MAG_RMS_START_TL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MAGSTABLEFG \
  "MAG_STABLE_FG"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MAGRMSVARTH \
  "MAG_RMS_VAR_TH"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_RPMVARRANGE \
  "RPM_VAR_RANGE"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_DECLOGICTEMPM \
  "DEC_LOGIC_TEMP_M"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_DECLOGICTEMPN \
  "DEC_LOGIC_TEMP_N"
#define \
  SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_DECLOGICLEARNNUMTEMP \
  "DEC_LOGIC_LEARN_NUM_TEMP"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_DECLOGICVIBM \
  "DEC_LOGIC_VIB_M"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_DECLOGICVIBN \
  "DEC_LOGIC_VIB_N"
#define \
  SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_DECLOGICLEARNNUMVIB \
  "DEC_LOGIC_LEARN_NUM_VIB"
#define \
  SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_DECLOGICLEARNNUMMAG \
  "DEC_LOGIC_LEARN_NUM_MAG"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMTEMP \
  "FUNC_ANOM_TEMP"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMOV \
  "FUNC_ANOM_OV"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMMECH \
  "FUNC_ANOM_MECH"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMBRG \
  "FUNC_ANOM_BRG"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMLUB \
  "FUNC_ANOM_LUB"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMMTR \
  "FUNC_ANOM_MTR"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMGEAR \
  "FUNC_ANOM_GEAR"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMFAN \
  "FUNC_ANOM_FAN"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FUNCANOMPUMP \
  "FUNC_ANOM_PUMP"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ASSETLEVEL \
  "ASSET_LEVEL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FLEXTYPE \
  "FLEX_TYPE"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_BOREDIAMETERMM \
  "BORE_DIAMETER_MM"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_RUNSPEEDRPM \
  "RUN_SPEED_RPM"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_BRGINFOBPFO \
  "BRG_INFO_BPFO"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_BRGINFOBPFI \
  "BRG_INFO_BPFI"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_BRGINFOBSF \
  "BRG_INFO_BSF"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_BRGINFOFTF \
  "BRG_INFO_FTF"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MTRINFOFL \
  "MTR_INFO_FL"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_MTRINFOBAR \
  "MTR_INFO_BAR"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_GEARINFOTOOTH \
  "GEAR_INFO_TOOTH"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_FANINFOBLADE \
  "FAN_INFO_BLADE"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_PUMPINFOVANE \
  "PUMP_INFO_VANE"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_TEMPOVALERTCDEGREE \
  "TEMP_OV_ALERT_CDEGREE"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ALARMTHRESHTEMP \
  "AlarmThrestemp"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ACCOVALERT \
  "ACC_OV_ALERT"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ACCOVALARM \
  "ACC_OV_ALARM"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ACCHALALERT \
  "ACC_HAL_ALERT"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ACCHALALARM \
  "ACC_HAL_ALARM"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_VELOVALERT \
  "VEL_OV_ALERT"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_VELOVALARM \
  "VEL_OV_ALARM"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_VELHALALERT \
  "VEL_HAL_ALERT"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_VELHALALARM \
  "VEL_HAL_ALARM"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ENVOVALERT \
  "ENV_OV_ALERT"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ENVOVALARM \
  "ENV_OV_ALARM"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ENVHALALERT \
  "ENV_HAL_ALERT"
#define SENSORCONFIGJSON_NAME_BULLETSENSORCONFIG_ALGOCFG_ENVHALALARM \
  "ENV_HAL_ALARM"

#endif /* __JSONNAME_H__ */
