/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.7 */

#include "DeviceAppBulletSensor.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SKFChina_App_AppMessage, SKFChina_App_AppMessage, 2)



