d /run/skf-gateway 0755 root root -
d /run/skf-gateway/ipc 0700 skfgw skfgw -
d /run/skf-gateway/requests 0700 skfgw skfgw -
d /run/skf-gateway/state 0750 root skfgw -
 
d /var/lib/skf-gateway 0700 skfgw skfgw -
d /var/lib/skf-gateway/config 0700 skfgw skfgw -
d /var/lib/skf-gateway/data 0700 skfgw skfgw -
d /var/lib/skf-gateway/update 0700 skfgw skfgw -

d /run/skf-gateway/hci-conn-update          0750 root  skfgw - -
d /run/skf-gateway/hci-conn-update/requests 0700 skfgw skfgw - -
d /run/skf-gateway/hci-conn-update/results  0750 root  skfgw - -

d /run/skf-gateway/network-recovery          0750 root  skfgw - -
d /run/skf-gateway/network-recovery/requests 0700 skfgw skfgw - -
d /run/skf-gateway/network-recovery/results  0750 root  skfgw - -