#ifndef __APP_GENERAL_DEF_H
#define __APP_GENERAL_DEF_H

#include <stdint.h>
#include "sys_def.h"

#include <signal.h>
#include "gwConfig.h"
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
#include "app_common.h"
#include <pthread.h>
#include <semaphore.h>
#endif

#ifndef MAX_BT_ADDRSTR
#define MAX_BT_ADDRSTR (0x20)
#endif
#ifndef MAX_IPC_MSG_PROTO_DATA
#define MAX_IPC_MSG_PROTO_DATA (400U)
#endif

#ifdef UNITTEST
#if ((UNITTEST == UNITTEST_MULTI_CONNECTION) || (UNITTEST == UNITTEST_MULTI_CON_SCAN_AND_PARSE_INSIGHT_T))
#define APP_GENERAL_DEF_MULTI_CON_REQUIRED (1)
#endif /* UNITTEST == UNITTEST_MULTI_CONNECTION */
#else /* UNITTEST */
#define APP_GENERAL_DEF_MULTI_CON_REQUIRED (0)
#endif /* UNITTEST */

/*********************************************************************/
/************************ IPC definitions ****************************/
/*********************************************************************/
/**
 * Message type of IPC
 */
enum msg_type
{
  M_TYPE_UNDEFINED = 0, // Unknown message type
  M_TYPE_COMMAND = 1,   // BLE command to control BLE PHY (from the process
                        // general to process BLE)
  M_TYPE_FEEDBACK = 2,  // ACK to the BLE command (if necessary) or other
                        // messages generated by process BLE (from process
                        // BLE to the process general)
  M_TYPE_PROTO_DATA = 3,// Froto data (directional)
                        // The sending Froto data
                        // is sent from process BLE to the process
                        // general
                        // The receiving Froto data
                        // is sent from the process general to process BLE
};
/**
 * BLE command to control BLE PHY (from the process general to process BLE)
 */
enum cmd_def
{
  CMD_UNDEFINED = 0,

  // From the process general to process BLE
  CMD_LOW_LEVEL_BLE_POWER_ON = 101,
  CMD_LOW_LEVEL_BLE_POWER_OFF = 102,
  CMD_LOW_LEVEL_BLE_SCAN_ON = 103,
  CMD_LOW_LEVEL_BLE_SCAN_OFF = 104,
  CMD_LOW_LEVEL_BLE_ADV_ON = 105,
  CMD_LOW_LEVEL_BLE_ADV_OFF = 106,
  CMD_DISCONNECTION = 6,  // to disconnect
  CMD_SET_WHITE_LIST = 7, // to set the device list (of connectable
                          // devices, e.g., predictSensor)
  // BT ROLE switch
  CMD_SW_TO_CLIENT = 1,
  CMD_SW_TO_SERVER = 2,

  // From process BLE to the process general
  CMD_NOTIFY = 3,  // Process BLE can use this command to notify a BLE
                   // event (e.g., disconnection or connection)

#if(APP_GENERAL_DEF_MULTI_CON_REQUIRED == 1)
  CMD_UPDATE_MULTI_CONNECTIONS = 200,
#endif

  // TODO: uncleaned ...

  CMD_ACQUIRE_GWID = 4,  // to get the GW-ID, the GW-ID is the BT-MAC
  CMD_SET_ACTIVE_BTCLIENT = 5,  // to set the active BT client, which means
                                // the GW will try to scan and connect the
                                // BT device with high priority
  //...
};
/**
 * The parameters used by BLE commands
 */
union msg_cmd_para
{
  struct bt_addr bt_white_list[MAX_BT_WHITE_LIST];  // For
                                                    // CMD_SET_WHITE_LIST
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
  // connection index: identify which con is the msg for.array type has incomplete element type
  // be sure to set it correctly before sending msg if necessary
  uint8_t connect_id[6];  // mac addr of sensor being connected. eg: 'C4BD6A110186'
#endif
  // TODO: uncleaned ...
  uint32_t tpu32;  // For test only
  uint8_t btdev_to_active[MAX_BT_ADDRSTR];  // For CMD_SET_ACTIVE_BTCLIENT
  uint8_t btdev_to_connect[MAX_BT_ADDRSTR];  // For CMD_DISCONNECTION
};
/**
 * Command message (from the process general to process BLE)
 */
struct msg_cmd
{
  enum cmd_def cmd;
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
  // connection index: identify which con is the msg for.array type has incomplete element type
  // be sure to set it correctly before sending msg if necessary
  uint8_t con_idx;
#endif
  uint32_t msgid;
  union msg_cmd_para para;
};
/**
 * Message including the connected device info 
 * (from process BLE to the process general)
 */
struct connected_device_info
{
  struct bt_addr adapterAddr; // The gateway's BLE MAC address
  struct bt_addr connected_dev;
};
/**
 * Bluetooth event notification
 */
struct bluetooth_event_notification
{
  enum bluetooth_event bt_event;  // like connection/disconnection
  union
  {
    struct connected_device_info dev; // The connected device's address used
                                      // when a connection is established
                                      // (i.e., the event is
                                      // BT_EVENT_CONNECTION)
    // TODO: uncleaned ...
    struct bt_addr connected_dev;  
    uint8_t active_bt_device[MAX_BT_ADDRSTR];  // temporary solution
  } info;
};

/**
 * Content of the message to the process general
 */
union msg_feedback_info
{
  struct bluetooth_event_notification event_notification_info;
  // TODO: uncleaned ...
  uint32_t tpu32;  // for test only
  //enum bluetooth_event notification_info; //the BT event
  uint8_t gw_id[MAX_ID_STR_LENGTH];
  //...
};
/**
 * Feedback message (from process BLE to the process general)
 */
struct msg_feedback
{
  enum cmd_def cmd; // @p CMD_NOTIFY of the corresponding command if it is
                    // an ACK
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
  // connection index: identify which con is the msg for.
  // be sure to set it correctly before sending msg if necessary
  uint8_t con_idx;
#if(APP_GENERAL_DEF_MULTI_CON_REQUIRED == 1)
  uint64_t con_start_time_ms;
#endif
#endif
  uint32_t msgid; // Corresponding command's msgid if it is an ACK
  union msg_feedback_info info;
};
/**
 * The received message (from process BLE to the process general)
 */
struct msg_proto_pkt_v3
{
  uint32_t len;
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
  // connection index: identify which con is the msg for.
  // be sure to set it correctly before sending msg if necessary
  uint8_t con_idx;
#endif
  uint8_t dtbuf[MAX_IPC_MSG_PROTO_DATA];
};

#if (SKF_GW_NEW == 1)
#define PROJECT_ID_FOR_SKF_GW_NEW_IPC (67)
// TODO: To check the access permission of "/tmp/" when a non-root user
// call the process
#ifndef FPATH_FOR_SKF_GW_NEW_IPC0
#define FPATH_FOR_SKF_GW_NEW_IPC0 "/run/skf-gateway/ipc/key0_new"
#endif
#ifndef FPATH_FOR_SKF_GW_NEW_IPC1
#define FPATH_FOR_SKF_GW_NEW_IPC1 "/run/skf-gateway/ipc/key1_new"
#endif
#define PERMISSION_FLAG_FOR_SKF_GW_NEW_IPC0 (0600)
#define PERMISSION_FLAG_FOR_SKF_GW_NEW_IPC1 (0600)

union msg_payload
{
  struct msg_cmd cmd_info;
  struct msg_feedback feedback_info;
  struct msg_proto_pkt_v3 proto_pkt;
};
/**
 * The structure of IPC message
 */
struct ipc_msg_v3
{
  long type;
  union msg_payload payload;
};
#endif /* SKF_GW_NEW == 1 */
#define PROJECT_ID_FOR_ICP (66)
// TODO: To check the access permission of "/tmp/" when a non-root user
// call the process
#ifndef FPATH_FOR_IPC0
#define FPATH_FOR_IPC0 "/run/skf-gateway/ipc/key0"
#endif
#ifndef FPATH_FOR_IPC1
#define FPATH_FOR_IPC1 "/run/skf-gateway/ipc/key1"
#endif
#define PERMISSION_FLAG_FOR_IPC0 (0600)
#define PERMISSION_FLAG_FOR_IPC1 (0600)

#if (1)
/**
 * Struct for thread sychronizaiotn 
 */
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
#define CONFIG_COND_VAR_MAGIC_INIT    (0x123456)
#define CONFIG_COND_VAR_MAGIC_DEINIT  (0x876543)
struct pthread_cond_var
{
  bool is_op_done;
  uint32_t para;
  pthread_mutex_t mtx;
  pthread_cond_t cond_var;
  pthread_condattr_t cattr;
  struct timespec tv;
  struct l_dbus_proxy *proxy;
#if (1)
  struct l_dbus_proxy *write_proxy; // add 1 more proxy for bt_gatt_n_write_data_to_peer_rx()
#endif
  uint32_t magic;
};
#else
struct pthread_cond_var
{
  bool is_op_done;
  uint32_t para;
  pthread_mutex_t mtx;
  pthread_cond_t cond_var;
  pthread_condattr_t cattr;
  struct timespec tv;
};
#endif  // "SKF_GW_CONFIG_MULTI_CONNECTION == 1"
#endif

// parameters for thandler_sensor_instance
#pragma pack(1)
struct parameter_sensor_instance
{
  uint8_t idx; // index of connection
  bool  used_flag;  // true for used/occupied
  uint8_t con_id[6]; // mac addr of sensor, in same format as connected_id of pro_general_controller.
#if (APP_GENERAL_DEF_MULTI_CON_REQUIRED == 1)
  uint64_t con_start_time_ms;
#endif
};
#pragma pack()
/* the device info in white list
*/
struct devinfo_node{
	uint32_t nameid;
	//uint8_t macstr[MAX_BT_ADDRSTR];
	uint8_t mac_bytes[6]; // nap(2B),uap(1B),lap(3B)
	uint8_t stype[GW_PRO_MAX_STRING_LEN_BYTE];
	//.......
};

/* the sensor type definition*/
enum sensortype{
	SS_TYPE_UNKNOWN = 0,
	SS_TYPE_INSIGHT_T = 1,
	SS_TYPE_PREDICT = 2,
	SS_TYPE_PREDICTP = 3
	//.....
};


// The controller for the process general
struct pro_general_controller
{
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
  bool bt_connection_flg[CONFIG_BLE_CONNECTION_MAX_NUM]; // True: when the gateway is in a connection
  pthread_mutex_t mtx_for_bt_connection;
  // add a flag for server role seperately
  bool bt_connection_server_flg;
#else
  bool bt_connection_flg; // True: when the gateway is in a connection
#endif

  // BT role
  enum bluetooth_role bt_role;
  bool bt_sw_in_progress;  // True when the BT mode switch is in progress
  pthread_mutex_t mtx_for_bt_sw;

  // IPC message sequence number
  uint32_t seq_no_counter;  // Message seq no
  pthread_mutex_t mtx_for_seq_no;

  // Basic information of addresses
  uint8_t gw_id[6];
#if (SKF_GW_CONFIG_MULTI_CONNECTION == 1)
  struct pthread_cond_var pt_gen_cond_var[CONFIG_BLE_CONNECTION_MAX_NUM]; // condition variables used by thread created for each connection/sensor
                                                                          // 1 cond_var per connection/sensor
  uint8_t connected_id[CONFIG_BLE_CONNECTION_MAX_NUM][6]; // mac addr of sensor being connected, in "C4BD6A11018B" format
  pthread_t thread_sensor[CONFIG_BLE_CONNECTION_MAX_NUM]; // thread id of created thread when connection(gw <-> sensor) setting up
  bool fg_is_services_resolved[CONFIG_BLE_CONNECTION_MAX_NUM]; // True when connection has been established
                                // and all the peer's services have been 
                                // discovered
  pthread_mutex_t mtx_for_service_flg;
#else
  uint8_t connected_id[6];
  bool fg_is_services_resolved; // True when connection has been established
                                // and all the peer's services have been 
                                // discovered
#endif  

  // TODO: uncleaned
  int hld_msg_to_pro_ble;
  int hld_msg_from_pro_ble;

  // TODO: uncleaned
  uint8_t gw_id_str[MAX_ID_STR_LENGTH];
  uint8_t active_client_id_str[MAX_BT_ADDRSTR];

  // the device list info
  struct devinfo_node dev_array[MAX_BT_WHITE_LIST];
  
  //..continue to add the other variable member you need here.....
};

// To control the output of bluez-dbus log output, set to none-zero to
// enable the log output which can be checked by "journalctl"
#ifndef BLUEZ_DBUS_LOG_ENABLE
#define BLUEZ_DBUS_LOG_ENABLE 0
#endif












#if (1)
#define MAX_IPC_MSG_BUF 512U

// the message type definition
struct ipc_msg
{
  long type;
  uint8_t dtbuf[MAX_IPC_MSG_BUF];
};

#endif

/*definition for data-unit to be send to bluetooth-peer
 */
struct data_unit
{
  uint32_t len;  // the len of data in the buffer below in bytes
  uint8_t *pt_buf;  // points to buffer where the data, remember to release
                    // the memory when it is not in use any more
};







struct msg_proto_pkt
{
  uint32_t len;
  uint8_t dtbuf[MAX_IPC_MSG_PROTO_DATA];
};
/*definition for command feedback
 */
/*struct ipc_msg_feedback{
   long mtype; // M_TYPE_FEEDBACK is the only valid value
   struct msg_feedback feedback_info;
   }; */

union msg_load
{
  struct msg_proto_pkt proto_pkt;  // NOTE!!! this is not a good solution
  struct msg_feedback feedback_info;
  struct msg_cmd cmd_info;
};

/*definition for protocol message
 */
struct ipc_msg_v2
{
  long mtype;  //
  union msg_load mtext;
};



struct longdata_xfer_ctr;

#define CLOCKID CLOCK_MONOTONIC
#define SIG_SHORTDATA_XFER_TIMEOUT (SIGRTMIN)  // signal for short data
                                               // transfer timeout
#define SIG_LONGDATA_XFER_TIMEOUT (SIGRTMIN + 1)  // signal for long data
                                                  // transfer timeout
#define SIG_TIMEOUT_SERVICE (SIGRTMIN + 2)  // signal for timeout service
#define SIG_DB_MODIFICATION_REPORT_TIMEOUT (SIGRTMIN + 3)  // signal for
                                                           // data
                                                           // modification
                                                           // report
                                                           // handler

#endif
