d /var/lib/skf-gateway                0700 skfgw skfgw -
d /var/lib/skf-gateway/config         0700 skfgw skfgw -
d /var/lib/skf-gateway/data           0700 skfgw skfgw -
d /var/lib/skf-gateway/update         0700 skfgw skfgw -
d /var/lib/skf-gateway/update/gateway 0700 skfgw skfgw -
d /var/lib/skf-gateway/update/sensor  0700 skfgw skfgw -
d /var/lib/skf-gateway/update/others  0700 skfgw skfgw -
d /run/skf-gateway                    0700 skfgw skfgw -
d /run/skf-gateway/ipc                0700 skfgw skfgw -